### ISSUE TITLE
【自研】【AJDK11】用例compiler/classUnloading/methodUnloading/TestOverloadCompileQueues.java在x64平台使用Xmixed -XX:+UseJadeGC选项概率超时失败

### ISSUE THREAD

**Issue by zhaoyuanfang1** [dragonwell-releng/dragonwell-adoptium#139]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/180465?tab=1
**Steps to Reproduce**
```
git clone -b master "https://code.alibaba-inc.com/xcode/jdk11" jdk-repo
mkdir binary-download/
cd binary-download/
wget -nv https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com//jade/20230511-163702-880-%23680-linux.x86_64.release.master-32ee088a7b4281cbbcc8f38f6a1f404f1496a315.jdk.tar.gz -O binary.tar.gz
tar zxvf binary.tar.gz
export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME
cd -
wget -nv https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg-6.1.1.zip -O jtreg.zip
unzip jtreg.zip
cd jtreg
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
wget -nv https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com//jade/20230511-163702-880-%23680-linux.x86_64.release.master-32ee088a7b4281cbbcc8f38f6a1f404f1496a315.test-image.tar.gz -O test-image.tar.gz
tar zxvf test-image.tar.gz
test=./jdk-repo/test/hotspot/jtreg/compiler/classUnloading/methodUnloading/TestOverloadCompileQueues.java
nproc=`nproc` ; dir="tmp-jtreg-"`basename $test .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 100 | xargs -i -n 1 -P $nproc bash -c "jtreg -ea -esa -Xmixed -XX:+UseJadeGC -nativepath:/home/admin/test/linux.x86_64.release.master-jtreg-test/test-image/hotspot/jtreg/native -timeoutFactor:2 -v:fail,error,time,nopass -nr -w $dir/index-{} $test &> $dir/{}.log ; grep 'Test results: passed: 1' -L $dir/{}.log"
```
错误日志

[5.log](https://github.com/dragonwell-releng/dragonwell-adoptium/files/11505042/5.log)
[84.log](https://github.com/dragonwell-releng/dragonwell-adoptium/files/11505043/84.log)
[32.log](https://github.com/dragonwell-releng/dragonwell-adoptium/files/11505044/32.log)
[4.log](https://github.com/dragonwell-releng/dragonwell-adoptium/files/11505045/4.log)
关键错误信息：
```
Timeout information:
Running jstack on process 3367389
2023-05-18 13:41:09
Full thread dump OpenJDK 64-Bit Server VM (11.0.18.18-AJDK+680-Alibaba mixed mode):

Threads class SMR info:
_java_thread_list=0x00007fb97540d040, length=10, elements={
0x00007fb9b6eb3000, 0x00007fb9b6eb4000, 0x00007fb9b6eb5000, 0x00007fb9b6eb6000,
0x00007fb9b6eb6800, 0x00007fb9b6eb7800, 0x00007fb9b6eb8800, 0x00007fb9b6eb9800,
0x00007fb9a8b9f000, 0x00007fb975414000
}

"main" #1 prio=5 os_prio=0 cpu=355.50ms elapsed=600.25s tid=0x00007fb9b6eb3000 nid=3367397 in Object.wait()  [0x00007fb9b9172000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.18.18-AJDK/Native Method)
	- waiting on <no object reference available>
	at java.lang.Thread.join(java.base@11.0.18.18-AJDK/Thread.java:1488)
	- waiting to re-lock in wait() <0x000000061a023118> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.18.18-AJDK/Thread.java:1563)
	at com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.41ms elapsed=599.96s tid=0x00007fb9b6eb4000 nid=3367521 waiting on condition  [0x00007fb9769fe000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.18.18-AJDK/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.18.18-AJDK/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.18.18-AJDK/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.29ms elapsed=599.95s tid=0x00007fb9b6eb5000 nid=3367529 in Object.wait()  [0x00007fb9765fe000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.18.18-AJDK/Native Method)
	- waiting on <0x000000061a023ff8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.18.18-AJDK/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x000000061a023ff8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.18.18-AJDK/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.18.18-AJDK/Finalizer.java:230)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.35ms elapsed=599.93s tid=0x00007fb9b6eb6000 nid=3367534 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.09ms elapsed=599.92s tid=0x00007fb9b6eb6800 nid=3367538 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 cpu=5465.29ms elapsed=599.92s tid=0x00007fb9b6eb7800 nid=3367539 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #7 daemon prio=9 os_prio=0 cpu=0.11ms elapsed=599.90s tid=0x00007fb9b6eb8800 nid=3367542 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #8 daemon prio=8 os_prio=0 cpu=0.71ms elapsed=599.63s tid=0x00007fb9b6eb9800 nid=3367679 in Object.wait()  [0x00007fb973ffe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.18.18-AJDK/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.18.18-AJDK/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x000000061a024998> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.18.18-AJDK/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11.0.18.18-AJDK/Thread.java:991)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.18.18-AJDK/InnocuousThread.java:161)

"MainThread" #10 prio=5 os_prio=0 cpu=267.14ms elapsed=599.45s tid=0x00007fb9a8b9f000 nid=3367758 waiting on condition  [0x00007fb9737d4000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Runtime.gc(java.base@11.0.18.18-AJDK/Native Method)
	at java.lang.System.gc(java.base@11.0.18.18-AJDK/System.java:1802)
	at compiler.classUnloading.methodUnloading.TestOverloadCompileQueues.run(TestOverloadCompileQueues.java:146)
	at compiler.classUnloading.methodUnloading.TestOverloadCompileQueues.main(TestOverloadCompileQueues.java:124)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.18.18-AJDK/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.18.18-AJDK/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.18.18-AJDK/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.18.18-AJDK/Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(java.base@11.0.18.18-AJDK/Thread.java:991)

"Attach Listener" #11 daemon prio=9 os_prio=0 cpu=0.17ms elapsed=0.10s tid=0x00007fb975414000 nid=3401421 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=12.66ms elapsed=600.00s tid=0x00007fb9b6e58000 nid=3367508 runnable  

"GC Thread#0" os_prio=0 cpu=1.20ms elapsed=600.25s tid=0x00007fb9b6e55000 nid=3367405 runnable  

"GC Thread#1" os_prio=0 cpu=0.86ms elapsed=599.02s tid=0x00007fb976a17000 nid=3367863 runnable  

"GC Thread#2" os_prio=0 cpu=0.85ms elapsed=599.01s tid=0x00007fb976a18000 nid=3367864 runnable  

"GC Thread#3" os_prio=0 cpu=1.04ms elapsed=599.00s tid=0x00007fb976a18800 nid=3367867 runnable  

"GC Thread#4" os_prio=0 cpu=0.74ms elapsed=598.98s tid=0x00007fb976a19800 nid=3367874 runnable  

"GC Thread#5" os_prio=0 cpu=0.81ms elapsed=598.97s tid=0x00007fb976a1a000 nid=3367883 runnable  

"GC Thread#6" os_prio=0 cpu=2.45ms elapsed=598.96s tid=0x00007fb976a1b000 nid=3367889 runnable  

"GC Thread#7" os_prio=0 cpu=0.70ms elapsed=598.95s tid=0x00007fb976a1b800 nid=3367894 runnable  

"GC Thread#8" os_prio=0 cpu=0.77ms elapsed=598.93s tid=0x00007fb976a1c800 nid=3367904 runnable  

"GC Thread#9" os_prio=0 cpu=0.98ms elapsed=598.93s tid=0x00007fb976a1d000 nid=3367905 runnable  

"GC Thread#10" os_prio=0 cpu=1.48ms elapsed=598.91s tid=0x00007fb976a1e000 nid=3367911 runnable  

"GC Thread#11" os_prio=0 cpu=0.77ms elapsed=598.90s tid=0x00007fb976a1e800 nid=3367914 runnable  

"GC Thread#12" os_prio=0 cpu=0.60ms elapsed=598.88s tid=0x00007fb976a1f800 nid=3367921 runnable  

"Jade Main Marker" os_prio=0 cpu=10.96ms elapsed=600.04s tid=0x00007fb9b6e56800 nid=3367496 runnable  

"Jade Conc#0" os_prio=0 cpu=8.40ms elapsed=600.02s tid=0x00007fb9b6e57800 nid=3367499 runnable  

"Jade Conc#1" os_prio=0 cpu=3.46ms elapsed=598.69s tid=0x00007fb988614000 nid=3367977 runnable  

"VM Periodic Task Thread" os_prio=0 cpu=182.33ms elapsed=599.64s tid=0x00007fb9b6e59000 nid=3367672 waiting on condition  

JNI global refs: 6, weak refs: 0

--- Timeout information end.
```
复现概率：4\100
默认-Xmixed选项测试：0/100
环境信息
![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/115980207/233a38e8-e5ce-4904-89cb-d9ac149a5006)

**Comment by sendaoYan** [comment]
[zhaoyuanfang1](https://github.com/zhaoyuanfang1) 提交的issue先关闭，后续有问题再重新打开
