### ISSUE TITLE
【AJDK11】用例vmTestbase/nsk/monitoring/stress/lowmem/lowmem034/TestDescription.java在x64平台失败, 手工执行未复现

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#200]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221477
Steps to Reproduce
```
cd binary-download/jdk-11.0.19.19+ &&  export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
cd jtreg/ && export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH && cd -
test=./jdk-repo/test/hotspot/jtreg/vmTestbase/nsk/monitoring/stress/lowmem/lowmem034/TestDescription.java
jtreg -w tmp -nr -v:fail,error -J-Djdk.lang.processReaperUseDefaultStackSize=true -J-Dtest.wisp.socketAddress=www.alibabacloud.com -J-XX:+UseJadeGC -J-ea -J-esa  $test

```

手工ajdk11 , 未复现,

```
--------------------------------------------------
TEST: vmTestbase/nsk/monitoring/stress/lowmem/lowmem034/TestDescription.java
TEST RESULT: Passed. Execution successful
--------------------------------------------------
Test results: passed: 1
Results written to /home/wb-wq628200/ajdk11/tmp
--------------------------------------------------
```
dragonwell11 , 手工未复现
```
--------------------------------------------------
TEST: vmTestbase/nsk/monitoring/stress/lowmem/lowmem034/TestDescription.java
TEST RESULT: Passed. Execution successful
--------------------------------------------------

```

tone: 错误日志
[TestDescription.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/12657018/TestDescription.txt)

```
STDERR:
nsk.share.TestFailure: Test exit code: 97
	at nsk.share.test.Tests$TestRunner.execute(Tests.java:90)
	at nsk.share.test.Tests$TestRunner.run(Tests.java:96)
	at nsk.share.gc.GC.runTest(GC.java:114)
	at nsk.monitoring.stress.lowmem.lowmem001.main(lowmem001.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:991)

JavaTest Message: Test threw exception: nsk.share.TestFailure: Test exit code: 97
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: nsk.share.TestFailure: Test exit code: 97


```
环境信息:

![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/32159229/67dfd806-b22a-45e9-9034-d001976a152e)

**Comment by sendaoYan** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/52368189# 《[ajdk11][jadegc]vmTestbase/nsk/monitoring/stress/lowmem/lowmem034随机失败》
