### ISSUE TITLE
【AJDK8】com/alibaba/cds 多个用例, 在x86-64/aarch64 平台 执行失败

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#201]
x86-64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221565?tab=1
aarch64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221566?tab=2
Steps to Reproduce
```
cd binary-download/jdk8u372-b/ && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
cd jtreg/ && export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH && cd -
test=./jdk-repo/jdk/test/com/alibaba/cds/TestDumpAndLoadClass.java
jtreg -w tmp -nr -v:fail,error  -Djdk.lang.processReaperUseDefaultStackSize=true -Dtest.wisp.socketAddress=www.alibabacloud.com -Xmixed -ea -esa $test
```
类似用例有: 
com/alibaba/cds/TestDumpAndLoadClass.java
com/alibaba/cds/TestDumpAndLoadClassWithException.java
com/alibaba/cds/TestDumpAndLoadClassWithNullURL.java
com/alibaba/cds/TestDumpAndLoadClassWithWisp.java
com/alibaba/cds/TestDumpAndLoadNotFound.java
com/alibaba/cds/TestDumpAndLoadVerficationFailure.java
com/alibaba/cds/TestDumpListInParallel.java
com/alibaba/cds/TestLoadClassFlow.java
com/alibaba/cds/TestSuppressingAppCDSErrors.java
com/alibaba/cds/TestWispWithAppCDS.java

case为此版本新增.

错误日志:
[TestDumpAndLoadClass.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/12657226/TestDumpAndLoadClass.txt)

```
[STDERR]
Error: Could not find or load main class com.alibaba.jvm.cds.Classes4CDS

[STDOUT]

STDERR:
 stdout: [];
 stderr: [Error: Could not find or load main class com.alibaba.jvm.cds.Classes4CDS
]
 exitValue = 1

java.lang.RuntimeException: Expected to get exit value of [0]

	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:396)
	at TestDumpAndLoadClass.convertClassList(TestDumpAndLoadClass.java:114)
	at TestDumpAndLoadClass.main(TestDumpAndLoadClass.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:879)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

```
![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/32159229/b7654d01-61f0-403f-adc3-87406436f348)

**Comment by owanqian** [comment]
构建流程目录错误, 关闭issue

**Comment by owanqian** [comment]
http://ci.jvm.alibaba.net/job/build-scripts/job/openjdk8-pipeline/186/artifact/target/linux/x64/ajdk/OpenJDK8U-jdk_x64_linux_ajdk_2023-09-21-03-33.tar.gz  验证通过

**Comment by owanqian** [comment]
新构建的又出现此问题:   https://tone.aliyun-inc.com/ws/xesljfzh/test_result/234495   包链接: http://114.55.64.175:8666/compiler-ci-bucket/ajdk8/20231013-003503-365-%23745-linux.aarch64.release.master-09bd2754db9858111837eeda17f5c21d33d01227.tar.gz

**Comment by owanqian** [comment]
http://114.55.64.175:8666/compiler-ci-bucket/ajdk8/20231013-103309-951-%23746-linux.x86_64.release.master-09bd2754db9858111837eeda17f5c21d33d01227.tar.gz 已修复
