### ISSUE TITLE
【AJDK8】com/alibaba/quickstart TestNotifyDump.java和TestNotifyDumpByJcmd.java 在x86-64/aarch64 平台 执行失败

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#202]
x86-64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221565?tab=1
aarch64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221566?tab=2
Steps to Reproduce
```
cd binary-download/jdk8u372-b/ && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
cd jtreg/ && export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH && cd -
test=./jdk-repo/jdk/test/com/alibaba/quickstart/TestNotifyDump.java
jtreg -w tmp -nr -v:fail,error  -Djdk.lang.processReaperUseDefaultStackSize=true -Dtest.wisp.socketAddress=www.alibabacloud.com -Xmixed -ea -esa $test
```
类似用例有: 
com/alibaba/quickstart/TestNotifyDump.java
com/alibaba/quickstart/TestNotifyDumpByJcmd.java

case为此版本新增.

错误日志:

[TestNotifyDump.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/12657358/TestNotifyDump.txt)

```
STDERR:
 stdout: [cache path is set from -Xquickstart:path=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/87/com/alibaba/quickstart/testnotifydump
Running as tracer
Error occurred during initialization of VM
Could not find agent library /tmp/tone/run/jtreg/binary-download/jdk8u372-b/jre/lib/amd64/serverless/libloadclassagent.so in absolute path, with error: /tmp/tone/run/jtreg/binary-download/jdk8u372-b/jre/lib/amd64/serverless/libloadclassagent.so: cannot open shared object file: No such file or directory
];
 stderr: []
 exitValue = 1

java.lang.RuntimeException: 'notifying dump done' missing from stdout/stderr 

	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:150)
	at TestNotifyDump.verifyPathSetting(TestNotifyDump.java:44)
	at TestNotifyDump.main(TestNotifyDump.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:879)

JavaTest Message: Test threw exception: java.lang.RuntimeException: 'notifying dump done' missing from stdout/stderr 

JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: 'notifying dump done' missing from stdout/stderr


```
![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/32159229/b7654d01-61f0-403f-adc3-87406436f348)

**Comment by owanqian** [comment]
构建流程目录错误, 关闭issue

**Comment by owanqian** [comment]
http://ci.jvm.alibaba.net/job/build-scripts/job/openjdk8-pipeline/186/artifact/target/linux/x64/ajdk/OpenJDK8U-jdk_x64_linux_ajdk_2023-09-21-03-33.tar.gz  验证通过
