### ISSUE TITLE
【AJDK8】com/alibaba/quickstart/TestAssemblyFiles.java 在x86-64/aarch64 平台 执行失败,缺少serverless jar包

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#204]
x86-64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221565?tab=1
aarch64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221566?tab=2
Steps to Reproduce
```
cd binary-download/jdk8u372-b/ && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
wget -nv https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg5.1-b01.zip -O jtreg.zip
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
git clone -b master "https://code.alibaba-inc.com/ajdk/jdk8u" jdk-repo
test=./jdk-repo/hotspot/test/multi-tenant/TestTenantNMTSupport.java
jtreg -w tmp -nr -v:fail,error  -Djdk.lang.processReaperUseDefaultStackSize=true -Dtest.wisp.socketAddress=www.alibabacloud.com -Xmixed -ea -esa $test
```

错误日志:
[TestAssemblyFiles.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/12657428/TestAssemblyFiles.txt)

com/alibaba/quickstart/TestAssemblyFiles.java

```
STDERR:
java.lang.RuntimeException: must have serverless/serverless-adapter.jar
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:407)
	at TestAssemblyFiles.verifyServerlessAdapter(TestAssemblyFiles.java:50)
	at TestAssemblyFiles.verifyAssemblyFiles(TestAssemblyFiles.java:41)
	at TestAssemblyFiles.main(TestAssemblyFiles.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:879)

JavaTest Message: Test threw exception: java.lang.RuntimeException: must have serverless/serverless-adapter.jar
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: must have serverless/serverless-adapter.jar




```
![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/32159229/b7654d01-61f0-403f-adc3-87406436f348)

**Comment by owanqian** [comment]
构建流程目录错误, 关闭issue

**Comment by owanqian** [comment]
http://ci.jvm.alibaba.net/job/build-scripts/job/openjdk8-pipeline/186/artifact/target/linux/x64/ajdk/OpenJDK8U-jdk_x64_linux_ajdk_2023-09-21-03-33.tar.gz  验证通过
