### ISSUE TITLE
【ajdk8】用例com/alibaba/quickstart/TestParallelProcessRun.java 在x86-64/aarch64 平台 超时失败

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#205]
x86-64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221565?tab=1
aarch64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221566?tab=2
Steps to Reproduce
```
cd binary-download/jdk8u372-b/ && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
wget -nv https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg5.1-b01.zip -O jtreg.zip
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
git clone -b master "https://code.alibaba-inc.com/ajdk/jdk8u" jdk-repo
test=./jdk-repo/jdk/test/com/alibaba/quickstart/TestParallelProcessRun.java
jtreg -w tmp -nr -v:fail,error  -Djdk.lang.processReaperUseDefaultStackSize=true -Dtest.wisp.socketAddress=www.alibabacloud.com -Xmixed -ea -esa $test
```

错误日志:
[TestParallelProcessRun.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/12657520/TestParallelProcessRun.txt)

com/alibaba/quickstart/TestParallelProcessRun.java

```
Timeout refired 2400 times
STDERR:
 stdout: [cache path is set from -Xquickstart:path=/tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/quickstart/TestParallelProcessRun/determine
Running as tracer
Error occurred during initialization of VM
Could not find agent library /tmp/tone/run/jtreg/binary-download/jdk8u372-b/jre/lib/amd64/serverless/libloadclassagent.so in absolute path, with error: /tmp/tone/run/jtreg/binary-download/jdk8u372-b/jre/lib/amd64/serverless/libloadclassagent.so: cannot open shared object file: No such file or directory
];
 stderr: []
 exitValue = 1

java.lang.RuntimeException: Expected to get exit value of [0]

	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:396)
	at TestParallelProcessRun.runAsTracer(TestParallelProcessRun.java:57)
	at TestParallelProcessRun.lambda$runAsTraceWithParallel$0(TestParallelProcessRun.java:41)
	at java.lang.Thread.run(Thread.java:879)


```
![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/32159229/b7654d01-61f0-403f-adc3-87406436f348)

**Comment by owanqian** [comment]
构建流程目录错误, 关闭issue
