### ISSUE TITLE
【AJDK8】com/alibaba/quickstart/TestDeterminingTracerOrReplayer.java / TestIntegrityCheck.java 和TestPrintStat.java 在x86-64/aarch64 平台 执行失败

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#210]
x86-64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221565?tab=1
aarch64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221566?tab=2
Steps to Reproduce
```
cd binary-download/jdk8u372-b/ && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
wget -nv https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg5.1-b01.zip -O jtreg.zip
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
git clone -b master "https://code.alibaba-inc.com/ajdk/jdk8u" jdk-repo
test=./jdk-repo/jdk/test/com/alibaba/quickstart/TestDeterminingTracerOrReplayer.java
jtreg -w tmp -nr -v:fail,error  -Djdk.lang.processReaperUseDefaultStackSize=true -Dtest.wisp.socketAddress=www.alibabacloud.com -Xmixed -ea -esa $test
```
同样错误用例:

com/alibaba/quickstart/TestIntegrityCheck.java
com/alibaba/quickstart/TestDeterminingTracerOrReplayer.java
com/alibaba/quickstart/TestPrintStat.java
错误日志:
[TestDeterminingTracerOrReplayer.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/12657713/TestDeterminingTracerOrReplayer.txt)

```
STDERR:
 stdout: [cache path is set from -Xquickstart:path=/tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/quickstart/TestDeterminingTracerOrReplayer/determine
Running as tracer
Error occurred during initialization of VM
Could not find agent library /tmp/tone/run/jtreg/binary-download/jdk8u372-b/jre/lib/amd64/serverless/libloadclassagent.so in absolute path, with error: /tmp/tone/run/jtreg/binary-download/jdk8u372-b/jre/lib/amd64/serverless/libloadclassagent.so: cannot open shared object file: No such file or directory
];
 stderr: []
 exitValue = 1

java.lang.RuntimeException: Expected to get exit value of [0]

	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:396)
	at TestDeterminingTracerOrReplayer.runAsTracer(TestDeterminingTracerOrReplayer.java:31)
	at TestDeterminingTracerOrReplayer.verifyDetermine(TestDeterminingTracerOrReplayer.java:23)
	at TestDeterminingTracerOrReplayer.main(TestDeterminingTracerOrReplayer.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:879)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]



```
![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/32159229/b7654d01-61f0-403f-adc3-87406436f348)

**Comment by owanqian** [comment]
构建流程目录错误, 关闭issue

**Comment by owanqian** [comment]
构建流程目录错误, 关闭issue

**Comment by owanqian** [comment]
http://ci.jvm.alibaba.net/job/build-scripts/job/openjdk8-pipeline/186/artifact/target/linux/x64/ajdk/OpenJDK8U-jdk_x64_linux_ajdk_2023-09-21-03-33.tar.gz    验证通过

**Comment by sendaoYan** [comment]
新版本还是失败的，麻烦确认下 @owanqian

**Comment by owanqian** [comment]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/233820?tab=2 已验证,pass

**Comment by owanqian** [comment]
http://114.55.64.175:8666/compiler-ci-bucket/ajdk8/20231014-003503-414-%23747-linux.aarch64.release.master-f444a55b2c0352fe75e25dfc4c0829226521afdf.tar.gz  此包此问题复现. 任务链接: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/235346?tab=3

**Comment by sendaoYan** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/52679572# 《[nightly][regress][ajdk8]com/alibaba/quickstart/TestDeterminingTracerOrReplayer.java报错libloadclassagent.so in absolute path》
