### ISSUE TITLE
【AJDK8】runtime/AppCDS/下5个用例 在x86-64/aarch64 平台 -XX:-UseCompressedOops  下执行失败

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#211]
x86-64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221565?tab=1
aarch64:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/221566?tab=2
Steps to Reproduce
```
cd binary-download/jdk8u372-b/ && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
wget -nv https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg5.1-b01.zip -O jtreg.zip
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
git clone -b master "https://code.alibaba-inc.com/ajdk/jdk8u" jdk-repo
test=./jdk-repo/hotspot/test/runtime/AppCDS/ParallelLoad.java
jtreg -w tmp -nr -v:fail,error  -J-Djdk.lang.processReaperUseDefaultStackSize=true -J-Dtest.wisp.socketAddress=www.alibabacloud.com -J-XX:-UseCompressedOops -J-ea -J-esa $test
```

类似用例
runtime/AppCDS/ArchiveSize.java
runtime/AppCDS/Hello.java
runtime/AppCDS/MissingSuper.java
runtime/AppCDS/Package.java
runtime/AppCDS/ParallelLoad.java

错误日志:

[Uploading ParallelLoad.txt…]()

```
STDERR:
 stdout: [[classpath: /tmp/tone/run/jtreg/jt-work/hotspot_test/classes/56/runtime/AppCDS/parallel_load.jar]
Error occurred during initialization of VM
Cannot dump shared archive when UseCompressedOops or UseCompressedClassPointers is off.
];
 stderr: []
 exitValue = 1

java.lang.RuntimeException: 'Loading classes to share' missing from stdout/stderr 

	at com.oracle.java.testlibrary.OutputAnalyzer.shouldContain(OutputAnalyzer.java:134)
	at TestCommon.testDump(TestCommon.java:218)
	at TestCommon.test(TestCommon.java:229)
	at ParallelLoad.main(ParallelLoad.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:879)

JavaTest Message: Test threw exception: java.lang.RuntimeException: 'Loading classes to share' missing from stdout/stderr 



```
![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/32159229/b7654d01-61f0-403f-adc3-87406436f348)

**Comment by owanqian** [comment]
构建流程目录错误, 关闭issue

**Comment by owanqian** [comment]
http://ci.jvm.alibaba.net/job/build-scripts/job/openjdk8-pipeline/186/artifact/target/linux/x64/ajdk/OpenJDK8U-jdk_x64_linux_ajdk_2023-09-21-03-33.tar.gz  验证通过

**Comment by sendaoYan** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/52572700# 《[ajdk8]runtime/AppCDS/下5个用例-XX:-UseCompressedOops报错Cannot dump shared archive when UseCompressedOops or UseCompressedClassPointers is off》

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14244725
