### ISSUE TITLE
【dragonwell8】在x86-64和aarch64报错bin下***.debuginfo: cannot execute binary file

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#215]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/229301?tab=1
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/229300

【环境准备】
```
wget  -O binary.tar.gz http://114.55.64.175:8666/compiler-ci-bucket/dragonwell8/20230901-002903-246-%23136-linux.aarch64.release.master-e0003979e233a5c036badfb5a7834e4b37e4f6cf.tar.gz 
tar xzvf binary.tar.gz
cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
wget -O jtreg.zip https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg5.1-b01.zip 
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
git clone -b master https://github.com/dragonwell-project/dragonwell8.git jdk-repo
test=./jdk-repo/jdk/test/tools/launcher/VersionCheck.java
args='-Xmixed -ea -esa'
jtreg -w tmp -nr -v:fail,error  $args $test
```

【对比测试】

dragonwell8 release 测试通过 
wget -O binary.tar.gz https://github.com/dragonwell-project/dragonwell8/releases/download/dragonwell-extended-8.16.17_jdk8u382-ga/Alibaba_Dragonwell_Extended_8.16.17_aarch64_linux.tar.gz

```
[root@VM20190228-137 dw8]# java -version ; java -Xinternalversion
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition 8.16.17) (build 1.8.0_382-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition 8.16.17) (build 25.382-b01, mixed mode)
OpenJDK 64-Bit Server VM (25.382-b01) for linux-amd64 JRE (1.8.0_382-b01), built on Aug  4 2023 07:24:01 by "jenkins" with gcc 7.5.0

```

【用例日志】
[完整日志.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/12745164/default.txt)

```
Actual:
/root/dw8/binary-download/bin/javah.debuginfo: /root/dw8/binary-download/bin/javah.debuginfo: cannot execute binary file
Error: /root/dw8/binary-download/bin/javah.debuginfo fails -J-fullversion comparison
Expected:
openjdk full version "1.8.0_372-b01"
Actual:
/root/dw8/binary-download/bin/javah.debuginfo: /root/dw8/binary-download/bin/javah.debuginfo: cannot execute binary file
Version Test: 90
STDERR:
java.lang.AssertionError: Some tests failed
  at VersionCheck.main(VersionCheck.java:228)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
  at java.lang.Thread.run(Thread.java:855)

JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.AssertionError: Some tests failed
```

【版本信息】
```
[root@VM20210305-10 dw8]# java -version; java -Xinternalversion
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition 8.16.17) (build 1.8.0_372-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition 8.16.17) (build 25.372-b01, mixed mode)
OpenJDK 64-Bit Server VM (25.372-b01) for linux-aarch64 JRE (1.8.0_372-b01), built on Aug 31 2023 16:27:35 by "" with gcc 7.5.0
```

**Comment by sendaoYan** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/52504456# 《[regress][dragonwell8]在x86-64和aarch64报错bin下***.debuginfo: cannot execute binary file》

**Comment by sendaoYan** [comment]
@Accelerator1996 

release版本bin目录：

![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/24123821/8f7e0778-a419-44e8-a252-63522bdd5dce)



nightly版本bin目录：

![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/24123821/b7de1b54-0a54-469a-981c-cf5951728ea3)
