### ISSUE TITLE
【dragonwell8】在x86-64平台multi-tenant下6个cgroup 用例出现create cgroup failed失败.

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#217]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/231942?tab=1

【环境准备】
```
wget  -O binary.tar.gz http://114.55.64.175:8666/compiler-ci-bucket/dragonwell8/20230901-002903-246-%23136-linux.x86_64.release.master-e0003979e233a5c036badfb5a7834e4b37e4f6cf.tar.gz
tar xzvf binary.tar.gz
cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
wget -O jtreg.zip https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg5.1-b01.zip 
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
git clone -b master https://github.com/dragonwell-project/dragonwell8.git jdk-repo
test=jdk-repo/jdk/test/multi-tenant/test/com/alibaba/tenant/TestJGroupInit.java
args='-Xmixed -ea -esa'
jtreg -w tmp -nr -v:fail,error  $args $test
```

【对比测试】
![lQLPJx-GtEQJx4jMv80CyLAcGHFS_PiOxgUTqMQH4QAA_712_191](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/32159229/ee5a80a8-8dfa-49cd-b113-2cc089f21cc3)
测试问题从8月5号开始: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/213603?tab=1
![lQLPJw1xYFJ54ojMzs0DBrBG3xLz42OuEgUTqOwjF_4A_774_206](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/32159229/76718386-290f-44c0-b8d7-ce14c2de74a3)
8月4号的nightly 是正常的: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/213158?tab=1

dragonwell8 release 测试同样问题. 
wget -O binary.tar.gz https://github.com/dragonwell-project/dragonwell8/releases/download/dragonwell-extended-8.16.17_jdk8u382-ga/Alibaba_Dragonwell_Extended_8.16.17_x64_linux.tar.gz

```
[root@VM20190228-137 dw8-release]#java -version; java -Xinternalversion
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition 8.16.17) (build 1.8.0_382-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition 8.16.17) (build 25.382-b01, mixed mode)
OpenJDK 64-Bit Server VM (25.382-b01) for linux-amd64 JRE (1.8.0_382-b01), built on Aug  4 2023 07:24:01 by "jenkins" with gcc 7.5.0

```

【用例日志】
multi-tenant/TestJGroupDebugMode.sh
multi-tenant/test/com/alibaba/tenant/TestJGroupInit.java
multi-tenant/test/com/alibaba/tenant/TestJMX.java
multi-tenant/test/com/alibaba/tenant/TestTenantConfiguration.java
jdk-repo/jdk/test/multi-tenant/test/com/alibaba/tenant/TestCpuCfsThrottling.java-rerun-10
jdk-repo/jdk/test/multi-tenant/test/com/alibaba/tenant/TestHierachicalTenants.java-rerun-10

```
STDERR:

ACTION: main -- Failed. Unexpected exit from test [exit code: 127]
REASON: User specified action: run main/othervm/bootclasspath -XX:+MultiTenant -XX:+TenantCpuThrottling -XX:+UseG1GC -Dcom.alibaba.tenant.DebugJGroup=true com.alibaba.tenant.TestJGroupInit 
TIME:   0.438 seconds
messages:
command: main -XX:+MultiTenant -XX:+TenantCpuThrottling -XX:+UseG1GC -Dcom.alibaba.tenant.DebugJGroup=true com.alibaba.tenant.TestJGroupInit
reason: User specified action: run main/othervm/bootclasspath -XX:+MultiTenant -XX:+TenantCpuThrottling -XX:+UseG1GC -Dcom.alibaba.tenant.DebugJGroup=true com.alibaba.tenant.TestJGroupInit 
Mode: othervm [/othervm specified, /bootclasspath specified]
elapsed time (seconds): 0.438
configuration:
STDOUT:
STDERR:
java.lang.RuntimeException: Failed to create cgroup at //ajdk_multi_tenant/3178085
	at com.alibaba.tenant.JGroup.initCgroupCommon(JGroup.java:257)
	at com.alibaba.tenant.JGroup.initSystemGroup(JGroup.java:235)
	at com.alibaba.tenant.JGroup.init(JGroup.java:139)
	at com.alibaba.tenant.JGroup.<init>(JGroup.java:130)
	at com.alibaba.tenant.JGroup.initializeJGroupClass(JGroup.java:395)

```

【版本信息】
```
[root@VM20190228-137 dw8]# !java
java -version; java -Xinternalversion
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition 8.16.17) (build 1.8.0_372-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition 8.16.17) (build 25.372-b01, mixed mode)
OpenJDK 64-Bit Server VM (25.372-b01) for linux-amd64 JRE (1.8.0_372-b01), built on Aug 31 2023 16:33:37 by "" with gcc 7.5.0
```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14208023 已经提交修复的PR，麻烦重新验证下 @owanqian

**Comment by owanqian** [comment]
通过, 关闭issue
