### ISSUE TITLE
【Ajdk8】x86-64平台renaissance-test测试finagle-chirper 用例执行失败,并导致任务超时

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#219]
aone任务: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/229431?tab=2
【环境准备】
```
ajdk 版本发布测试
wget http://114.55.64.175:8666/ajdk-backup/test-52/OpenJDK8U-jdk_aarch64_linux_ajdk_2023-09-25-09-23.tar.gz
```
【测试步骤】
此步骤并没有复现,此问题. 正常执行成功.
```
wget http://114.55.64.175:8666/ajdk-backup/test-52/OpenJDK8U-jdk_aarch64_linux_ajdk_2023-09-25-09-23.tar.gz -O binary.tar.gz
mkdir binary-download
tar xzvf binary.tar.gz -C binary-download
cd binary-download 
export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME
cd -
wget http://114.55.64.175:8666/compiler-ci-bucket/jdk/tools/renaissance-0.14.2/plugin-jmxmemory-assembly-0.0.1.jar plugin-jmxmemory-assembly-0.0.1.jar
wget http://114.55.64.175:8666/compiler-ci-bucket/jdk/tools/renaissance-0.14.2/plugin-jmxtimers-assembly-0.0.2.jar plugin-jmxtimers-assembly-0.0.2.jar
wget http://114.55.64.175:8666/compiler-ci-bucket/jdk/tools/renaissance-0.14.2/plugin-ubenchagent-assembly-0.0.1.jar plugin-ubenchagent-assembly-0.0.1.jar
wget http://114.55.64.175:8666/compiler-ci-bucket/jdk/tools/renaissance-0.14.2/renaissance-gpl-0.14.2.jar renaissance-gpl-0.14.2.jar
wget http://114.55.64.175:8666/compiler-ci-bucket/jdk/tools/renaissance-0.14.2/renaissance-jmh-0.14.2.jar renaissance-jmh-0.14.2.jar
wget http://114.55.64.175:8666/compiler-ci-bucket/jdk/tools/renaissance-0.14.2/renaissance-mit-0.14.2.jar renaissance-mit-0.14.2.jar
echo 3 > /proc/sys/vm/drop_caches
java -Xmixed  -jar renaissance-gpl-0.14.2.jar --with-arg -Xmixed  --csv result.csv --json result.json --keep-scratch all
```
【用例日志】

t-one重新验证问题依然存在: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/232509

```
====== finagle-chirper (web) [default], iteration 0 started ======
Resetting master, feed map size: 5000
GC before operation: completed in 1418.682 ms, heap usage 812.011 MB -> 392.961 MB.
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
Exception in thread "Thread-24134" Failure(Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel at remote address: localhost/127.0.0.1:45413. Remote Info: Not Available, flags=0x08) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: localhost/127.0.0.1:45413, Downstream label: :45413, Trace Id: 30f20783b26c8e12.4eb2983bcb267e60<:c629041b7f943a59 with Service -> :45413
Caused by: com.twitter.finagle.ConnectionFailedException: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel at remote address: localhost/127.0.0.1:45413. Remote Info: Not Available
        at com.twitter.finagle.netty4.ConnectionBuilder$$anon$1.operationComplete(ConnectionBuilder.scala:105)
        at com.twitter.finagle.netty4.ConnectionBuilder$$anon$1.operationComplete(ConnectionBuilder.scala:84)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
        at com.twitter.finagle.netty4.ConnectionBuilder.build(ConnectionBuilder.scala:84)
        at com.twitter.finagle.netty4.Netty4Transporter$$anon$1.apply(Netty4Transporter.scala:45)
        at com.twitter.finagle.http2.transport.client.H2CTransporter.apply(H2CTransporter.scala:30)
        at com.twitter.finagle.http.TransporterServiceFactory.$anonfun$apply$1(TransporterServiceFactory.scala:28)
        at com.twitter.util.Local.letClear(Local.scala:5004)
        at com.twitter.finagle.context.MarshalledContext.letClearAll(MarshalledContext.scala:130)
        at com.twitter.finagle.context.Contexts$.$anonfun$letClearAll$1(Contexts.scala:39)
        at com.twitter.util.Local.letClear(Local.scala:5004)
        at com.twitter.finagle.context.LocalContext.letClearAll(LocalContext.scala:43)
        at com.twitter.finagle.context.Contexts$.letClearAll(Contexts.scala:38)
        at com.twitter.finagle.http.TransporterServiceFactory.apply(TransporterServiceFactory.scala:28)
        at com.twitter.finagle.ServiceFactory$$anon$1.apply(ServiceFactory.scala:46)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:120)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:120)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:120)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:120)
        at com.twitter.finagle.pool.CachingPool.apply(CachingPool.scala:90)
        at com.twitter.finagle.pool.WatermarkPool.apply(WatermarkPool.scala:194)
        at com.twitter.finagle.http2.transport.client.H2Pool.apply(H2Pool.scala:151)
        at com.twitter.finagle.liveness.FailureAccrualFactory.apply(FailureAccrualFactory.scala:424)
        at com.twitter.finagle.client.ExceptionRemoteInfoFactory.apply(ExceptionRemoteInfoFactory.scala:110)
        at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:14)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:120)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:120)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:120)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:120)
        at com.twitter.finagle.loadbalancer.LazyEndpointFactory.apply(EndpointFactory.scala:116)
        at com.twitter.finagle.loadbalancer.TrafficDistributor$EndpointFactoryProxy$1.apply(TrafficDistributor.scala:57)
        at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:14)
        at com.twitter.finagle.loadbalancer.p2c.P2CLeastLoaded$Node.com$twitter$finagle$loadbalancer$LeastLoaded$LeastLoadedNode$$super$apply(P2CLeastLoaded.scala:44)
        at com.twitter.finagle.loadbalancer.LeastLoaded$LeastLoadedNode.apply(LeastLoaded.scala:27)
        at com.twitter.finagle.loadbalancer.LeastLoaded$LeastLoadedNode.apply$(LeastLoaded.scala:25)
        at com.twitter.finagle.loadbalancer.p2c.P2CLeastLoaded$Node.apply(P2CLeastLoaded.scala:44)
        at com.twitter.finagle.loadbalancer.Balancer.apply(Balancer.scala:226)
        at com.twitter.finagle.loadbalancer.Balancer.apply$(Balancer.scala:214)
        at com.twitter.finagle.loadbalancer.p2c.P2CLeastLoaded.apply(P2CLeastLoaded.scala:33)
        at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:14)
        at com.twitter.finagle.loadbalancer.TrafficDistributor$Distributor.apply(TrafficDistributor.scala:164)
        at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:14)
        at com.twitter.finagle.loadbalancer.TrafficDistributor.apply(TrafficDistributor.scala:357)
        at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:14)
        at com.twitter.finagle.factory.StatsFactoryWrapper.apply(StatsFactoryWrapper.scala:42)
        at com.twitter.finagle.ServiceFactory$$anon$1.apply(ServiceFactory.scala:46)
        at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:14)
        at com.twitter.finagle.factory.TimeoutFactory.apply(TimeoutFactory.scala:77)
        at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:120)
        at com.twitter.finagle.ServiceFactory.apply(ServiceFactory.scala:27)
        at com.twitter.finagle.FactoryToService.apply(FactoryToService.scala:12)
        at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
        at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
        at com.twitter.finagle.service.RequeueFilter.$anonfun$issueRequest$1(RequeueFilter.scala:82)
        at com.twitter.util.Local.let(Local.scala:4979)
        at com.twitter.finagle.context.MarshalledContext.letLocal(MarshalledContext.scala:194)
        at com.twitter.finagle.context.MarshalledContext.let(MarshalledContext.scala:105)
        at com.twitter.finagle.service.RequeueFilter.issueRequest(RequeueFilter.scala:69)
        at com.twitter.finagle.service.RequeueFilter.$anonfun$applyService$1(RequeueFilter.scala:145)
        at com.twitter.util.Local.let(Local.scala:4979)
        at com.twitter.finagle.context.MarshalledContext.letLocal(MarshalledContext.scala:194)
        at com.twitter.finagle.context.MarshalledContext.let(MarshalledContext.scala:105)
        at com.twitter.finagle.tracing.Trace$.letId(Trace.scala:102)
        at com.twitter.finagle.service.RequeueFilter.applyService(RequeueFilter.scala:145)
        at com.twitter.finagle.service.RequeueFilter.$anonfun$issueRequest$3(RequeueFilter.scala:109)
        at com.twitter.util.Promise$FutureTransformer.liftedTree1$1(Promise.scala:258)
        at com.twitter.util.Promise$FutureTransformer.k(Promise.scala:258)
        at com.twitter.util.Promise$Transformer.apply(Promise.scala:233)
        at com.twitter.util.Promise$WaitQueue.run(Promise.scala:104)
        at com.twitter.util.Promise$WaitQueue.$anonfun$runInScheduler$1(Promise.scala:97)
        at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:167)
        at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:126)
        at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:243)
        at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:78)
        at com.twitter.util.Promise$WaitQueue.runInScheduler(Promise.scala:97)
        at com.twitter.util.Promise.updateIfEmpty(Promise.scala:808)
        at com.twitter.util.Promise.update(Promise.scala:780)
        at com.twitter.util.Promise.setException(Promise.scala:763)
        at com.twitter.finagle.netty4.ConnectionBuilder$$anon$1.operationComplete(ConnectionBuilder.scala:99)
        at com.twitter.finagle.netty4.ConnectionBuilder$$anon$1.operationComplete(ConnectionBuilder.scala:84)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
        at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502)
        at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:240)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:879)
Caused by: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.epoll.EpollSocketChannel
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:46)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:310)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
        at com.twitter.finagle.netty4.ConnectionBuilder.build(ConnectionBuilder.scala:71)
        ... 84 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor874.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:44)
        ... 88 more
Caused by: io.netty.channel.ChannelException: io.netty.channel.unix.Errors$NativeIoException: newSocketStream(..) failed: Too many open files
        at io.netty.channel.unix.Socket.newSocketStream0(Socket.java:503)
        at io.netty.channel.epoll.LinuxSocket.newSocketStream(LinuxSocket.java:331)
        at io.netty.channel.epoll.LinuxSocket.newSocketStream(LinuxSocket.java:335)
        at io.netty.channel.epoll.EpollSocketChannel.<init>(EpollSocketChannel.java:49)
        ... 92 more
Caused by: io.netty.channel.unix.Errors$NativeIoException: newSocketStream(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
[finagle/netty4/boss-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.


```

【环境信息】
```
#uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25 ; java -version ; java -Xinternalversion
Linux t50b11120.sqa.eu95 3.10.0-327.ali2019.alios7.x86_64 #1 SMP Sun Jan 19 18:21:42 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora anolis"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"
HOME_URL="https://os.alibaba-inc.com/"
BUG_REPORT_URL="https://os.alibaba-inc.com/"

ALIBABA_BUGZILLA_PRODUCT="Alibaba Group Enterprise Linux 7"
ALIBABA_BUGZILLA_PRODUCT_VERSION=7.2
ALIBABA_SUPPORT_PRODUCT="Alibaba Group Enterprise Linux"
ALIBABA_SUPPORT_PRODUCT_VERSION=7.2
              total        used        free      shared  buff/cache   available
Mem:           503G         13G        484G        3.6M        5.8G        488G
Swap:          2.0G          0B        2.0G
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                96
On-line CPU(s) list:   0-95
Thread(s) per core:    2
Core(s) per socket:    24
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
Stepping:              4
CPU MHz:               2500.000
CPU max MHz:           3100.0000
CPU min MHz:           1000.0000
BogoMIPS:              4998.90
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              33792K
NUMA node0 CPU(s):     0-95
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb invpcid_single pln pts dtherm spec_ctrl ibpb_support tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt avx512f avx512dq rdseed adx smap clflushopt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local cat_l3 mba
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Alibaba 8.20.24) (build 1.8.0_372-b2)
OpenJDK 64-Bit Server VM (Alibaba 8.20.24) (build 25.372-b2, mixed mode)
OpenJDK 64-Bit Server VM (25.372-b2) for linux-amd64 JRE (1.8.0_372-b2), built on Sep 25 2023 09:27:56 by "root" with gcc 4.8.2 20140120 (Red Hat 4.8.2-15)
```

**Comment by sendaoYan** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/52542174# 《[ajdk8]x86-64平台renaissance-test测试finagle-chirper报newSocketStream(..) failed: Too many open files》
