### ISSUE TITLE
【regress】ajdk11 - compiler/aot/DeoptimizationTest.java用例失败

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-releng/dragonwell-adoptium#22]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148193?tab=1

```
found working linker: /bin/ld
Command line: [/home/yansendao/software/jdk/2023-02/ajdk/jdk-11.0.17.16+/bin/jaotc -J-XX:-UseCompressedOops -J-classpath -J/home/yansendao/git/dragonwell11/tmp/classes/compiler/aot/DeoptimizationTest.d:/home/yansendao/git/dragonwell11/tmp/classes/test/lib:/home/yansendao/git/dragonwell11/tmp/classes/testlibrary:/home/yansendao/git/dragonwell11/tmp/classes:/home/yansendao/git/dragonwell11/test/hotspot/jtreg/compiler/aot --compile-with-assertions --info --output libDeoptimizationTest.so --compile-commands methodsList.txt --class-name compiler.aot.DeoptimizationTest -J-ea -J-esa -J-Xmixed]
[2023-02-23T12:16:33.246252Z] Gathering output for process 1517794
Compiling libDeoptimizationTest.so...
1 classes found (12 ms)
VM config values not expected to be present in JDK 11 linux-amd64 (java.home=/home/yansendao/software/jdk/2023-02/ajdk/jdk-11.0.17.16+, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=11.0.17.16-AJDK+0-Alibaba):
    UseShenandoahGC [value: false]
Set the JVMCI_CONFIG_CHECK environment variable to "ignore" to suppress this error or to "warn" to emit a warning and continue execution.
Currently used Java home directory is /home/yansendao/software/jdk/2023-02/ajdk/jdk-11.0.17.16+.
Currently used VM configuration is: OpenJDK 64-Bit Server VM

6 methods total, 1 methods to compile (5 ms)
Compiling with 16 threads
.
1 methods compiled, 0 methods failed (347 ms)
Parsing compiled code (1 ms)
Exception in thread "main" org.graalvm.compiler.debug.GraalError: Unsupported metaspace constant type: null
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.phases.aot.ReplaceConstantNodesPhase.handleHotSpotMetaspaceConstant(ReplaceConstantNodesPhase.java:457)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.phases.aot.ReplaceConstantNodesPhase.replaceKlassesAndObjects(ReplaceConstantNodesPhase.java:552)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.phases.aot.ReplaceConstantNodesPhase.run(ReplaceConstantNodesPhase.java:586)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.phases.aot.ReplaceConstantNodesPhase.run(ReplaceConstantNodesPhase.java:83)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:221)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:237)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.stubs.Stub.buildCompilationResult(Stub.java:235)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.stubs.Stub.getCompilationResult(Stub.java:251)
        at jdk.aot@11.0.17.16-AJDK/jdk.tools.jaotc.DataBuilder.retrieveStubCode(DataBuilder.java:191)
        at jdk.aot@11.0.17.16-AJDK/jdk.tools.jaotc.DataBuilder.prepareData(DataBuilder.java:147)
        at jdk.aot@11.0.17.16-AJDK/jdk.tools.jaotc.Main.run(Main.java:344)
        at jdk.aot@11.0.17.16-AJDK/jdk.tools.jaotc.Main.run(Main.java:169)
        at jdk.aot@11.0.17.16-AJDK/jdk.tools.jaotc.Main.main(Main.java:106)

[2023-02-23T12:16:34.390330Z] Waiting for completion for process 1517794
[2023-02-23T12:16:34.390418Z] Waiting for completion finished for process 1517794
[2023-02-23T12:16:34.390514Z] Waiting for completion for process 1517794
[2023-02-23T12:16:34.390561Z] Waiting for completion finished for process 1517794
STDERR:
 stdout: [Compiling libDeoptimizationTest.so...
1 classes found (12 ms)
VM config values not expected to be present in JDK 11 linux-amd64 (java.home=/home/yansendao/software/jdk/2023-02/ajdk/jdk-11.0.17.16+, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=11.0.17.16-AJDK+0-Alibaba):
    UseShenandoahGC [value: false]
Set the JVMCI_CONFIG_CHECK environment variable to "ignore" to suppress this error or to "warn" to emit a warning and continue execution.
Currently used Java home directory is /home/yansendao/software/jdk/2023-02/ajdk/jdk-11.0.17.16+.
Currently used VM configuration is: OpenJDK 64-Bit Server VM

6 methods total, 1 methods to compile (5 ms)
Compiling with 16 threads
.
1 methods compiled, 0 methods failed (347 ms)
Parsing compiled code (1 ms)
Exception in thread "main" org.graalvm.compiler.debug.GraalError: Unsupported metaspace constant type: null
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.phases.aot.ReplaceConstantNodesPhase.handleHotSpotMetaspaceConstant(ReplaceConstantNodesPhase.java:457)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.phases.aot.ReplaceConstantNodesPhase.replaceKlassesAndObjects(ReplaceConstantNodesPhase.java:552)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.phases.aot.ReplaceConstantNodesPhase.run(ReplaceConstantNodesPhase.java:586)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.phases.aot.ReplaceConstantNodesPhase.run(ReplaceConstantNodesPhase.java:83)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:221)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:237)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.stubs.Stub.buildCompilationResult(Stub.java:235)
        at jdk.internal.vm.compiler@11.0.17.16-AJDK/org.graalvm.compiler.hotspot.stubs.Stub.getCompilationResult(Stub.java:251)
        at jdk.aot@11.0.17.16-AJDK/jdk.tools.jaotc.DataBuilder.retrieveStubCode(DataBuilder.java:191)
        at jdk.aot@11.0.17.16-AJDK/jdk.tools.jaotc.DataBuilder.prepareData(DataBuilder.java:147)
        at jdk.aot@11.0.17.16-AJDK/jdk.tools.jaotc.Main.run(Main.java:344)
        at jdk.aot@11.0.17.16-AJDK/jdk.tools.jaotc.Main.run(Main.java:169)
        at jdk.aot@11.0.17.16-AJDK/jdk.tools.jaotc.Main.main(Main.java:106)
];
 stderr: []
 exitValue = 1

java.lang.RuntimeException: Expected to get exit value of [0]

        at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
        at compiler.aot.AotCompiler.main(AotCompiler.java:79)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:125)
        at java.base/java.lang.Thread.run(Thread.java:991)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

JavaTest Message: shutting down test
```

![image](https://user-images.githubusercontent.com/24123821/220903480-d505bb33-eef6-4778-9bcc-e3bb047c902f.png)

dragonwell11:

![image](https://user-images.githubusercontent.com/24123821/220903600-9cdadc59-40ff-4bed-86c0-b8af3e120dc3.png)

**Comment by sendaoYan** [comment]
如下62个用例暂时归类未同一个问题
```
compiler/aot/DeoptimizationTest.java
compiler/aot/RecompilationTest.java
compiler/aot/SharedUsageTest.java
compiler/aot/TestHeapBase.java
compiler/aot/appaot/InlineTest.sh
compiler/aot/appaot/InterfaceInlineTest.sh
compiler/aot/appaot/TestAppAOT.sh
compiler/aot/appaot/TestIncorrectCallerForInlinedCallee.sh
compiler/aot/appaot/TestMultipleLoaders.sh
compiler/aot/appaot/TestTieredAOT.sh
compiler/aot/appaot/TestUnboundLoader.sh
compiler/aot/appaot/TestUnmatchedCompressedOops.sh
compiler/aot/calls/fromAot/AotInvokeDynamic2AotTest.java
compiler/aot/calls/fromAot/AotInvokeDynamic2CompiledTest.java
compiler/aot/calls/fromAot/AotInvokeDynamic2InterpretedTest.java
compiler/aot/calls/fromAot/AotInvokeDynamic2NativeTest.java
compiler/aot/calls/fromAot/AotInvokeInterface2AotTest.java
compiler/aot/calls/fromAot/AotInvokeInterface2CompiledTest.java
compiler/aot/calls/fromAot/AotInvokeInterface2InterpretedTest.java
compiler/aot/calls/fromAot/AotInvokeInterface2NativeTest.java
compiler/aot/calls/fromAot/AotInvokeSpecial2AotTest.java
compiler/aot/calls/fromAot/AotInvokeSpecial2CompiledTest.java
compiler/aot/calls/fromAot/AotInvokeSpecial2InterpretedTest.java
compiler/aot/calls/fromAot/AotInvokeSpecial2NativeTest.java
compiler/aot/calls/fromAot/AotInvokeStatic2AotTest.java
compiler/aot/calls/fromAot/AotInvokeStatic2CompiledTest.java
compiler/aot/calls/fromAot/AotInvokeStatic2InterpretedTest.java
compiler/aot/calls/fromAot/AotInvokeStatic2NativeTest.java
compiler/aot/calls/fromAot/AotInvokeVirtual2AotTest.java
compiler/aot/calls/fromAot/AotInvokeVirtual2CompiledTest.java
compiler/aot/calls/fromAot/AotInvokeVirtual2InterpretedTest.java
compiler/aot/calls/fromAot/AotInvokeVirtual2NativeTest.java
compiler/aot/calls/fromCompiled/CompiledInvokeDynamic2AotTest.java
compiler/aot/calls/fromCompiled/CompiledInvokeInterface2AotTest.java
compiler/aot/calls/fromCompiled/CompiledInvokeSpecial2AotTest.java
compiler/aot/calls/fromCompiled/CompiledInvokeStatic2AotTest.java
compiler/aot/calls/fromCompiled/CompiledInvokeVirtual2AotTest.java
compiler/aot/calls/fromInterpreted/InterpretedInvokeDynamic2AotTest.java
compiler/aot/calls/fromInterpreted/InterpretedInvokeInterface2AotTest.java
compiler/aot/calls/fromInterpreted/InterpretedInvokeSpecial2AotTest.java
compiler/aot/calls/fromInterpreted/InterpretedInvokeStatic2AotTest.java
compiler/aot/calls/fromInterpreted/InterpretedInvokeVirtual2AotTest.java
compiler/aot/calls/fromNative/NativeInvokeSpecial2AotTest.java
compiler/aot/calls/fromNative/NativeInvokeStatic2AotTest.java
compiler/aot/calls/fromNative/NativeInvokeVirtual2AotTest.java
compiler/aot/cli/DisabledAOTWithLibraryTest.java
compiler/aot/cli/MultipleAOTLibraryTest.java
compiler/aot/cli/SingleAOTLibraryTest.java
compiler/aot/cli/SingleAOTOptionTest.java
compiler/aot/cli/jaotc/AtFileTest.java
compiler/aot/cli/jaotc/CompileClassTest.java
compiler/aot/cli/jaotc/CompileClassWithDebugTest.java
compiler/aot/cli/jaotc/CompileDirectoryTest.java
compiler/aot/cli/jaotc/CompileJarTest.java
compiler/aot/cli/jaotc/CompileModuleTest.java
compiler/aot/cli/jaotc/IgnoreErrorsTest.java
compiler/aot/cli/jaotc/ListOptionTest.java
compiler/aot/cli/jaotc/ListOptionWrongFileTest.java
compiler/aot/fingerprint/SelfChanged.java
compiler/aot/fingerprint/SelfChangedCDS.java
compiler/aot/fingerprint/SuperChanged.java
compiler/aot/verification/ClassAndLibraryNotMatchTest.java
```
[aot.log](https://github.com/dragonwell-releng/dragonwell-adoptium/files/10813423/aot.log)

**Comment by sendaoYan** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/59322171# 《[ajdk11]compiler/aot/DeoptimizationTest.java报错Exception in thread "main" org.graalvm.compiler.debug.GraalError: Unsupported metaspace constant type: null》
