### ISSUE TITLE
【dragonwell11】在aarch64平台runtime/NMT/SummarySanityCheck.java报异常:Total committed  did not match the summarized committed .

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#222]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/233241
【环境准备】
```
wget -O binary.tar.gz http://114.55.64.175:8666/compiler-ci-bucket/dragonwell11/20231010-003904-273-%23121-linux.aarch64.release.master-f3ff21fe2ffedf2fdfd8b14486f38123ba81ea4a.jdk.tar.gz
mkdir binary-download
tar xzvf binary.tar.gz -C binary-download
cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
wget http://114.55.64.175:8666/compiler-ci-bucket/dragonwell11/20231010-003904-273-%23121-linux.aarch64.release.master-f3ff21fe2ffedf2fdfd8b14486f38123ba81ea4a.test-image.tar.gz -O test-image.tar.gz
make test-image
tar xzvf test-image.tar.gz -C test-image
wget -O jtreg.zip https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg-6.1.1.zip
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
git clone -b master https://github.com/dragonwell-project/dragonwell11.git jdk-repo
test=jdk-repo/test/hotspot/jtreg/runtime/NMT/SummarySanityCheck.java
args='-Xmixed -ea -esa'
native='-nativepath:./test-image/hotspot/jtreg/native'
jtreg -w tmp -nr -v:fail,error $native  $args $test
```

【对比测试】

dragonwell11 release版本PASS.
wget -O binary.tar.gz https://dragonwell.oss-cn-shanghai.aliyuncs.com/11.0.20.17.8/Alibaba_Dragonwell_Extended_11.0.20.17.8_aarch64_linux.tar.gz

```
[root@VM20210305-10 dw11-release]# java -version ; java -Xinternalversion
openjdk version "11.0.20.17" 2023-07-18
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition)-11.0.20.17+8-GA (build 11.0.20.17+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition)-11.0.20.17+8-GA (build 11.0.20.17+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.20.17+8) for linux-aarch64 JRE (11.0.20.17+8), built on Sep  7 2023 02:12:09 by "" with gcc 7.5.0
```

【用例日志】
在上一个构建版本上,是通过的
http://114.55.64.175:8666/compiler-ci-bucket/dragonwell11/20230922-003903-230-%23103-linux.aarch64.release.master-ea25b10279ef102e7c6786e1c04d44f950f0a7d8.jdk.tar.gz

[完整日志.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/12864313/default.txt)

```
STDERR:

ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Exception: Total committed (1181454) did not match the summarized committed (18014398510663437) . Stdout is : 343463: Native Memory Tracking: Total: reserved=18065682KB, committed=1181454KB - Java Heap (reserved=16019456KB, committed=1003520KB) (mmap: reserved=16019456KB, committed=1003520KB) - Class (reserved=1056991KB, committed=9055KB) (classes #1222) ( instance classes #1077, array classes #145) (malloc=223KB #1947) (mmap: reserved=1056768KB, committed=8832KB) ( Metadata: ) ( reserved=8192KB, committed=7936KB) ( used=7580KB) ( free=356KB) ( waste=0KB =0.00%) ( Class space:) ( reserved=1048576KB, committed=896KB) ( used=761KB) ( free=135KB) ( waste=0KB =0.00%) - Thread (reserved=53367KB, committed=29479KB) (thread #26) (stack: reserved=53248KB, committed=29360KB) (malloc=96KB #158) (arena=24KB #45) - Code (reserved=247802KB, committed=8566KB) (malloc=114KB #941) (mmap: reserved=247688KB, committed=8452KB) - GC (reserved=679381KB, committed=122149KB) (malloc=49665KB #2302) (mmap: reserved=629716KB, committed=72484KB) - Compiler (reserved=1796KB, committed=1796KB) (malloc=14KB #98) (arena=1783KB #59) - Internal (reserved=592KB, committed=592KB) (malloc=560KB #1123) (mmap: reserved=32KB, committed=32KB) - Other (reserved=2KB, committed=2KB) (malloc=2KB #1) - Symbol (reserved=2760KB, committed=2760KB) (malloc=1537KB #4589) (arena=1223KB #1) - Native Memory Tracking (reserved=219KB, committed=219KB) (malloc=6KB #80) (tracking overhead=213KB) - Arena Chunk (reserved=3314KB, committed=3314KB) (malloc=3314KB) - Logging (reserved=5KB, committed=5KB) (malloc=5KB #203) - Arguments (reserved=18014398509481873KB, committed=18014398509481873KB) (malloc=20KB #532) (arena=18014398509481852KB #18446744073709551612) - Module (reserved=60KB, committed=60KB) (malloc=60KB #1068) - Synchronizer (reserved=39KB, committed=39KB) (malloc=39KB #328) - Safepoint (reserved=8KB, committed=8KB) (mmap: reserved=8KB, committed=8KB)
REASON: User specified action: run main/othervm -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+WhiteBoxAPI SummarySanityCheck 
TIME:   0.705 seconds
messages:
command: main -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+WhiteBoxAPI SummarySanityCheck
reason: User specified action: run main/othervm -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+WhiteBoxAPI SummarySanityCheck 
Mode: othervm [/othervm specified]
Additional options from @modules: --add-modules java.base,java.management --add-exports java.base/jdk.internal.misc=ALL-UNNAMED
elapsed time (seconds): 0.705
configuration:
Boot Layer
  add modules: java.base java.management   
  add exports: java.base/jdk.internal.misc ALL-UNNAMED

STDOUT:
[2023-10-10T17:13:38.495019Z] Gathering output for process 343588
STDERR:
java.lang.Exception: Total committed (1181454) did not match the summarized committed (18014398510663437) . Stdout is :
343463:

Native Memory Tracking:

Total: reserved=18065682KB, committed=1181454KB
-                 Java Heap (reserved=16019456KB, committed=1003520KB)
                            (mmap: reserved=16019456KB, committed=1003520KB) 
 
-                     Class (reserved=1056991KB, committed=9055KB)
                            (classes #1222)
                            (  instance classes #1077, array classes #145)
                            (malloc=223KB #1947) 
                            (mmap: reserved=1056768KB, committed=8832KB) 
                            (  Metadata:   )
                            (    reserved=8192KB, committed=7936KB)
                            (    used=7580KB)
                            (    free=356KB)
                            (    waste=0KB =0.00%)
                            (  Class space:)
                            (    reserved=1048576KB, committed=896KB)
                            (    used=761KB)
                            (    free=135KB)
                            (    waste=0KB =0.00%)
 
-                    Thread (reserved=53367KB, committed=29479KB)
                            (thread #26)
                            (stack: reserved=53248KB, committed=29360KB)
                            (malloc=96KB #158) 
                            (arena=24KB #45)
 
-                      Code (reserved=247802KB, committed=8566KB)
                            (malloc=114KB #941) 
                            (mmap: reserved=247688KB, committed=8452KB) 
 
-                        GC (reserved=679381KB, committed=122149KB)
                            (malloc=49665KB #2302) 
                            (mmap: reserved=629716KB, committed=72484KB) 
 
-                  Compiler (reserved=1796KB, committed=1796KB)
                            (malloc=14KB #98) 
                            (arena=1783KB #59)
 
-                  Internal (reserved=592KB, committed=592KB)
                            (malloc=560KB #1123) 
                            (mmap: reserved=32KB, committed=32KB) 
 
-                     Other (reserved=2KB, committed=2KB)
                            (malloc=2KB #1) 
 
-                    Symbol (reserved=2760KB, committed=2760KB)
                            (malloc=1537KB #4589) 
                            (arena=1223KB #1)
 
-    Native Memory Tracking (reserved=219KB, committed=219KB)
                            (malloc=6KB #80) 
                            (tracking overhead=213KB)
 
-               Arena Chunk (reserved=3314KB, committed=3314KB)
                            (malloc=3314KB) 
 
-                   Logging (reserved=5KB, committed=5KB)
                            (malloc=5KB #203) 
 
-                 Arguments (reserved=18014398509481873KB, committed=18014398509481873KB)
                            (malloc=20KB #532) 
                            (arena=18014398509481852KB #18446744073709551612)
 
-                    Module (reserved=60KB, committed=60KB)
                            (malloc=60KB #1068) 
 
-              Synchronizer (reserved=39KB, committed=39KB)
                            (malloc=39KB #328) 
 
-                 Safepoint (reserved=8KB, committed=8KB)
                            (mmap: reserved=8KB, committed=8KB) 
 

	at SummarySanityCheck.throwTestException(SummarySanityCheck.java:118)
	at SummarySanityCheck.main(SummarySanityCheck.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:955)

JavaTest Message: Test threw exception: java.lang.Exception: Total committed (1181454) did not match the summarized committed (18014398510663437) . Stdout is :
343463:

Native Memory Tracking:

Total: reserved=18065682KB, committed=1181454KB
-                 Java Heap (reserved=16019456KB, committed=1003520KB)
                            (mmap: reserved=16019456KB, committed=1003520KB) 
 
-                     Class (reserved=1056991KB, committed=9055KB)
                            (classes #1222)
                            (  instance classes #1077, array classes #145)
                            (malloc=223KB #1947) 
                            (mmap: reserved=1056768KB, committed=8832KB) 
                            (  Metadata:   )
                            (    reserved=8192KB, committed=7936KB)
                            (    used=7580KB)
                            (    free=356KB)
                            (    waste=0KB =0.00%)
                            (  Class space:)
                            (    reserved=1048576KB, committed=896KB)
                            (    used=761KB)
                            (    free=135KB)
                            (    waste=0KB =0.00%)
 
-                    Thread (reserved=53367KB, committed=29479KB)
                            (thread #26)
                            (stack: reserved=53248KB, committed=29360KB)
                            (malloc=96KB #158) 
                            (arena=24KB #45)
 
-                      Code (reserved=247802KB, committed=8566KB)
                            (malloc=114KB #941) 
                            (mmap: reserved=247688KB, committed=8452KB) 
 
-                        GC (reserved=679381KB, committed=122149KB)
                            (malloc=49665KB #2302) 
                            (mmap: reserved=629716KB, committed=72484KB) 
 
-                  Compiler (reserved=1796KB, committed=1796KB)
                            (malloc=14KB #98) 
                            (arena=1783KB #59)
 
-                  Internal (reserved=592KB, committed=592KB)
                            (malloc=560KB #1123) 
                            (mmap: reserved=32KB, committed=32KB) 
 
-                     Other (reserved=2KB, committed=2KB)
                            (malloc=2KB #1) 
 
-                    Symbol (reserved=2760KB, committed=2760KB)
                            (malloc=1537KB #4589) 
                            (arena=1223KB #1)
 
-    Native Memory Tracking (reserved=219KB, committed=219KB)
                            (malloc=6KB #80) 
                            (tracking overhead=213KB)
 
-               Arena Chunk (reserved=3314KB, committed=3314KB)
                            (malloc=3314KB) 
 
-                   Logging (reserved=5KB, committed=5KB)
                            (malloc=5KB #203) 
 
-                 Arguments (reserved=18014398509481873KB, committed=18014398509481873KB)
                            (malloc=20KB #532) 
                            (arena=18014398509481852KB #18446744073709551612)
 
-                    Module (reserved=60KB, committed=60KB)
                            (malloc=60KB #1068) 
 
-              Synchronizer (reserved=39KB, committed=39KB)
                            (malloc=39KB #328) 
 
-                 Safepoint (reserved=8KB, committed=8KB)
                            (mmap: reserved=8KB, committed=8KB) 
 

JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.Exception: Total committed (1181454) did not match the summarized committed (18014398510663437) . Stdout is : 343463: Native Memory Tracking: Total: reserved=18065682KB, committed=1181454KB - Java Heap (reserved=16019456KB, committed=1003520KB) (mmap: reserved=16019456KB, committed=1003520KB) - Class (reserved=1056991KB, committed=9055KB) (classes #1222) ( instance classes #1077, array classes #145) (malloc=223KB #1947) (mmap: reserved=1056768KB, committed=8832KB) ( Metadata: ) ( reserved=8192KB, committed=7936KB) ( used=7580KB) ( free=356KB) ( waste=0KB =0.00%) ( Class space:) ( reserved=1048576KB, committed=896KB) ( used=761KB) ( free=135KB) ( waste=0KB =0.00%) - Thread (reserved=53367KB, committed=29479KB) (thread #26) (stack: reserved=53248KB, committed=29360KB) (malloc=96KB #158) (arena=24KB #45) - Code (reserved=247802KB, committed=8566KB) (malloc=114KB #941) (mmap: reserved=247688KB, committed=8452KB) - GC (reserved=679381KB, committed=122149KB) (malloc=49665KB #2302) (mmap: reserved=629716KB, committed=72484KB) - Compiler (reserved=1796KB, committed=1796KB) (malloc=14KB #98) (arena=1783KB #59) - Internal (reserved=592KB, committed=592KB) (malloc=560KB #1123) (mmap: reserved=32KB, committed=32KB) - Other (reserved=2KB, committed=2KB) (malloc=2KB #1) - Symbol (reserved=2760KB, committed=2760KB) (malloc=1537KB #4589) (arena=1223KB #1) - Native Memory Tracking (reserved=219KB, committed=219KB) (malloc=6KB #80) (tracking overhead=213KB) - Arena Chunk (reserved=3314KB, committed=3314KB) (malloc=3314KB) - Logging (reserved=5KB, committed=5KB) (malloc=5KB #203) - Arguments (reserved=18014398509481873KB, committed=18014398509481873KB) (malloc=20KB #532) (arena=18014398509481852KB #18446744073709551612) - Module (reserved=60KB, committed=60KB) (malloc=60KB #1068) - Synchronizer (reserved=39KB, committed=39KB) (malloc=39KB #328) - Safepoint (reserved=8KB, committed=8KB) (mmap: reserved=8KB, committed=8KB)


```

【版本信息】
```
[root@VM20210305-10 dw11]# uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25 ; java -version ; java -Xinternalversion
Linux VM20210305-10 4.19.91-26.an8.aarch64 #1 SMP Tue May 24 13:14:10 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
NAME="Anolis OS"
VERSION="8.6"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.6"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.6"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

              total        used        free      shared  buff/cache   available
Mem:           15Gi       349Mi       6.1Gi       0.0Ki       9.0Gi        14Gi
Swap:            0B          0B          0B
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per cluster: 4
Socket(s):           2
Cluster(s):          1
NUMA node(s):        1
Vendor ID:           HiSilicon
BIOS Vendor ID:      Alibaba Cloud
Model:               0
Model name:          Kunpeng-920
BIOS Model name:     virt-rhel7.6.0
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
openjdk version "11.0.20-internal" 2023-07-18
OpenJDK Runtime Environment (build 11.0.20-internal+0-adhoc..dragonwell11.nightly.pipeline)
OpenJDK 64-Bit Server VM (build 11.0.20-internal+0-adhoc..dragonwell11.nightly.pipeline, mixed mode)
OpenJDK 64-Bit Server VM (11.0.20-internal+0-adhoc..dragonwell11.nightly.pipeline) for linux-aarch64 JRE (11.0.20-internal+0-adhoc..dragonwell11.nightly.pipeline), built on Oct  9 2023 16:39:47 by "" with gcc 7.5.0


```

**Comment by sendaoYan** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/52590219# 《[regress][nightly][dragonwell11]aarch64平台runtime/NMT/SummarySanityCheck.java报错》

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14257089

**Comment by owanqian** [comment]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/234510?tab=2 验证通过
