### ISSUE TITLE
【AJDK11】用例hotspot/jtreg/metaspace-dump/MetaspaceDumpTest.java在x64/aarch64平台报错:assertTrue: expected true, was false

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#224]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/233704?tab=3

【环境准备】
```
wget -O binary.tar.gz http://114.55.64.175:8666/compiler-ci-bucket/ajdk11/20231011-004603-491-%23419-linux.aarch64.release.master-5e957aec541366986f8a777112e3fe35267873da.jdk.tar.gz
mkdir binary-download
tar xzvf binary.tar.gz -C binary-download
cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
wget http://114.55.64.175:8666/compiler-ci-bucket/ajdk11/20231011-004603-491-%23419-linux.aarch64.release.master-5e957aec541366986f8a777112e3fe35267873da.test-image.tar.gz -O test-image.tar.gz
make test-image
tar xzvf test-image.tar.gz -C test-image
wget -O jtreg.zip https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg-6.1.1.zip
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
git clone -b master https://github.com/dragonwell-project/dragonwell11.git jdk-repo
test=jdk-repo/test/hotspot/jtreg/metaspace-dump/MetaspaceDumpTest.java
args='-Xmixed -ea -esa'
native='-nativepath:./test-image/hotspot/jtreg/native'
jtreg -w tmp -nr -v:fail,error $native  $args $test
```

【对比测试】

之前通过的nightly 构建版本, 现在测试也是同样问题. 

a11 release版本同样问题.
wget -O binary.tar.gz http://114.55.64.175:8666/ajdk-backup/11.0.19.19/OpenJDK11U-jdk_aarch64_linux_ajdk_2023-06-27-09-52.tar.gz
wget -O test-image.tar.gz http://114.55.64.175:8666/ajdk-backup/11.0.19.19/OpenJDK11U-testimage_aarch64_linux_ajdk_2023-06-27-09-52.tar.gz
```
openjdk version "11.0.19.19-AJDK" 2023-06-27
OpenJDK Runtime Environment (Alibaba AJDK) (build 11.0.19.19-AJDK+306-Alibaba)
OpenJDK 64-Bit Server VM (Alibaba AJDK) (build 11.0.19.19-AJDK+306-Alibaba, mixed mode)
OpenJDK 64-Bit Server VM (11.0.19.19-AJDK+306-Alibaba) for linux-aarch64 JRE (11.0.19.19-AJDK+306-Alibaba), built on Jun 27 2023 09:53:31 by "" with gcc 7.3.1 20180303 (Red Hat 7.3.1-5)

```

【用例日志】
[完整日志.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/12876758/default.txt)

```
STDERR:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by MetaspaceDumpTest (file:/disk1/a11-old/jt-work/classes/metaspace-dump/MetaspaceDumpTest.d/) to field java.lang.ProcessImpl.pid
WARNING: Please consider reporting this to the maintainers of MetaspaceDumpTest
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.RuntimeException: assertTrue: expected true, was false
        at jdk.test.lib.Asserts.fail(Asserts.java:594)
        at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
        at jdk.test.lib.Asserts.assertTrue(Asserts.java:472)
        at MetaspaceDumpTest.checkFile(MetaspaceDumpTest.java:89)
        at MetaspaceDumpTest.main(MetaspaceDumpTest.java:74)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:991)

JavaTest Message: Test threw exception: java.lang.RuntimeException: assertTrue: expected true, was false
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: assertTrue: expected true, was false

```

【版本信息】
```
[root@VM20210305-10 a11]# uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25 ; java -version ; java -Xinternalversion
Linux VM20210305-10 4.19.91-26.an8.aarch64 #1 SMP Tue May 24 13:14:10 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
NAME="Anolis OS"
VERSION="8.6"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.6"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.6"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

              total        used        free      shared  buff/cache   available
Mem:           15Gi       356Mi       310Mi       0.0Ki        14Gi        14Gi
Swap:            0B          0B          0B
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per cluster: 4
Socket(s):           2
Cluster(s):          1
NUMA node(s):        1
Vendor ID:           HiSilicon
BIOS Vendor ID:      Alibaba Cloud
Model:               0
Model name:          Kunpeng-920
BIOS Model name:     virt-rhel7.6.0
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
openjdk version "11.0.20.20-AJDK" 2023-10-11
OpenJDK Runtime Environment (build 11.0.20.20-AJDK+0-Alibaba)
OpenJDK 64-Bit Server VM (build 11.0.20.20-AJDK+0-Alibaba, mixed mode)
OpenJDK 64-Bit Server VM (11.0.20.20-AJDK+0-Alibaba) for linux-aarch64 JRE (11.0.20.20-AJDK+0-Alibaba), built on Oct 10 2023 16:46:49 by "" with gcc 7.3.1 20180303 (Red Hat 7.3.1-5)

```

**Comment by sendaoYan** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/52618055# 《[regress][nightly]metaspace-dump/MetaspaceDumpTest.java在x64/aarch64平台报错》
