### ISSUE TITLE
【dragonwell11】在aarch64平台-XX:-UseCompressedOops 选项下java/math/BigInteger/largeMemory/SymmetricRangeTests.java报:Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#231]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/238019

【环境准备】
```
wget -O jtreg.zip https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg-6.1.1.zip
wget -O binary.tar.gz https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-57/OpenJDK11U-jdk_aarch64_linux_dragonwell_2023-10-19-06-15.tar.gz
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-57/OpenJDK11U-testimage_aarch64_linux_dragonwell_2023-10-19-06-15.tar.gz -O test-image.tar.gz
git clone https://github.com/dragonwell-project/dragonwell11.git jdk-repo -b wip_dragonwell_standard_merge_branch

mkdir binary-download 
tar xzvf binary.tar.gz -C binary-download ; cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME &&cd -
make test-image ; tar xzvf test-image.tar.gz -C test-image
unzip jtreg.zip; cd jtreg ; export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH ; cd -

args='-XX:-UseCompressedOops -ea -esa'
native='-nativepath:./test-image/hotspot/jtreg/native'
test=jdk-repo/test/jdk/java/math/BigInteger/largeMemory/SymmetricRangeTests.java

dir="jt-work" ; rm -rf $dir ; mkdir -p $dir ; time seq 4000 | xargs -i -n 1 -P 1  bash -c "jtreg -w tmp -nr -v:fail,error $native  $args $test &> $dir/test-{}.log ; grep 'Test results: passed: 1' -L $dir/test-{}.log"

```

【对比测试】

dragonwell11 release版本同样错误.
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/11.0.20.16.8/Alibaba_Dragonwell_Standard_11.0.20.16.8_aarch64_linux.tar.gz

```
[root@VM20210305-10 dw11-release]# java -version; java -Xinternalversion
openjdk version "11.0.20.16" 2023-07-18
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.20.16+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.20.16+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.20.16+8) for linux-aarch64 JRE (11.0.20.16+8), built on Aug  8 2023 07:33:37 by "" with gcc 7.5.0


```
temurin11 同样错误.
wget https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.21%2B9/OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.21_9.tar.gz
```
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)
OpenJDK 64-Bit Server VM Temurin-11.0.21+9 (build 11.0.21+9, mixed mode)
OpenJDK 64-Bit Server VM (11.0.21+9) for linux-aarch64 JRE (11.0.21+9), built on Oct 17 2023 21:44:42 by "" with gcc 7.5.0

```

【用例日志】

```
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
REASON: User specified action: run main/timeout=180/othervm -Xmx8g -XX:+CompactStrings SymmetricRangeTests
TIME:   0.921 seconds
messages:
command: main -Xmx8g -XX:+CompactStrings SymmetricRangeTests
reason: User specified action: run main/timeout=180/othervm -Xmx8g -XX:+CompactStrings SymmetricRangeTests
Mode: othervm [/othervm specified]
elapsed time (seconds): 0.921
configuration:
STDOUT:
Testing overflow in BigInteger.makePositive
STDERR:
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at SymmetricRangeTests.testOverflowInMakePositive(SymmetricRangeTests.java:88)
        at SymmetricRangeTests.main(SymmetricRangeTests.java:624)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:829)

JavaTest Message: Test threw exception: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.OutOfMemoryError: Requested array size exceeds VM limit

```

【版本信息】

```
[root@VM20210305-10 d11]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;java -version; java -Xinternalversion
Linux VM20210305-10 4.19.91-26.an8.aarch64 #1 SMP Tue May 24 13:14:10 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
NAME="Anolis OS"
VERSION="8.6"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.6"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.6"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

              total        used        free      shared  buff/cache   available
Mem:           15Gi       377Mi       807Mi       0.0Ki        14Gi        14Gi
Swap:            0B          0B          0B
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per cluster: 4
Socket(s):           2
Cluster(s):          1
NUMA node(s):        1
Vendor ID:           HiSilicon
BIOS Vendor ID:      Alibaba Cloud
Model:               0
Model name:          Kunpeng-920
BIOS Model name:     virt-rhel7.6.0
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
openjdk version "11.0.21.16" 2023-10-17
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.21.16+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.21.16+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.21.16+8) for linux-aarch64 JRE (11.0.21.16+8), built on Oct 19 2023 06:21:50 by "" with gcc 7.5.0

```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14503373
