### ISSUE TITLE
【dragonwell17】在x86-64/aarch64平台security/infra/java/security/cert/CertPathValidator/certification/CertignaRoots.java : timed out

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#232]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/239360
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/239361

【环境准备】
```
wget -O jtreg.zip https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg-6.1.1.zip
wget -O binary.tar.gz https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-58/OpenJDK17U-jdk_aarch64_linux_dragonwell_2023-10-23-02-59.tar.gz
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-58/OpenJDK17U-testimage_aarch64_linux_dragonwell_2023-10-23-02-59.tar.gz -O test-image.tar.gz
git clone https://github.com/dragonwell-project/dragonwell17.git -b wip_dragonwell_standard_merge_branch jdk-repo

mkdir binary-download 
tar xzvf binary.tar.gz -C binary-download ; cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME &&cd -
make test-image ; tar xzvf test-image.tar.gz -C test-image
unzip jtreg.zip; cd jtreg ; export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH ; cd -

test=jdk-repo/test/jdk/security/infra/java/security/cert/CertPathValidator/certification/CertignaRoots.java
args='-Xmixed -ea -esa'
native='-nativepath:./test-image/hotspot/jtreg/native'
jtreg -w tmp -nr -v:fail,error $native  $args $test
```

【对比测试】

dragonwell17 release版本同样错误.
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/17.0.8.0.8%2B7/Alibaba_Dragonwell_Standard_17.0.8.0.8%2B7_aarch64_linux.tar.gz

```
[root@VM20210305-10 d17-release]# java -version; java -Xinternalversion
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.8.0.8+7-GA (build 17.0.8+7)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.8.0.8+7-GA (build 17.0.8+7, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.8+7) for linux-aarch64 JRE (17.0.8+7), built on Jul 18 2023 00:00:00 by "dragonwell" with gcc 10.3.0

```

temurin17 同样错误.
wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.9%2B9/OpenJDK17U-jdk_aarch64_linux_hotspot_17.0.9_9.tar.gz
```
[root@VM20210305-10 t17]# java -version; java -Xinternalversion
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.9+9) for linux-aarch64 JRE (17.0.9+9), built on Oct 17 2023 00:00:00 by "admin" with gcc 10.3.0

```

【用例日志】
[完整日志.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/13175588/default.txt)

```
STDERR:

ACTION: main -- Error. Program `/disk1/d17/binary-download/bin/java' timed out (timeout set to 120000ms, elapsed time including timeout handling was 120317ms).
REASON: User specified action: run main/othervm -Djava.security.debug=certpath CertignaRoots OCSP
TIME:   120.322 seconds
messages:
command: main -Djava.security.debug=certpath CertignaRoots OCSP
reason: User specified action: run main/othervm -Djava.security.debug=certpath CertignaRoots OCSP
Mode: othervm [/othervm specified]
Timeout information:
Running jstack on process 3473409
2023-10-26 17:17:08
Full thread dump OpenJDK 64-Bit Server VM (17.0.9+7 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x0000ffff64001710, length=13, elements={
0x0000ffffb40272b0, 0x0000ffffb417eb50, 0x0000ffffb417ffd0, 0x0000ffffb41894b0,
0x0000ffffb418a900, 0x0000ffffb418bd40, 0x0000ffffb418d6b0, 0x0000ffffb418ec10,
0x0000ffffb41980a0, 0x0000ffffb41a02a0, 0x0000ffffb41a3700, 0x0000ffffb41c9e50,
0x0000ffff64000cd0
}

"main" #1 prio=5 os_prio=0 cpu=74.10ms elapsed=120.29s tid=0x0000ffffb40272b0 nid=0x350004 in Object.wait()  [0x0000ffffb899e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.9/Native Method)
        - waiting on <0x00000007097e1a00> (a java.lang.Thread)
        at java.lang.Thread.join(java.base@17.0.9/Thread.java:1313)
        - locked <0x00000007097e1a00> (a java.lang.Thread)
        at java.lang.Thread.join(java.base@17.0.9/Thread.java:1381)
        at com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.33ms elapsed=120.26s tid=0x0000ffffb417eb50 nid=0x35000b waiting on condition  [0x0000ffff907fd000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@17.0.9/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@17.0.9/Reference.java:253)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@17.0.9/Reference.java:215)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.33ms elapsed=120.26s tid=0x0000ffffb417ffd0 nid=0x35000c in Object.wait()  [0x0000ffff905ff000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.9/Native Method)
        - waiting on <0x00000007097f7f30> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.9/ReferenceQueue.java:155)
        - locked <0x00000007097f7f30> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.9/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@17.0.9/Finalizer.java:172)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.37ms elapsed=120.26s tid=0x0000ffffb41894b0 nid=0x35000d waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.18ms elapsed=120.26s tid=0x0000ffffb418a900 nid=0x35000e runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Deflation Thread" #6 daemon prio=9 os_prio=0 cpu=5.64ms elapsed=120.26s tid=0x0000ffffb418bd40 nid=0x35000f runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=0 cpu=546.44ms elapsed=120.26s tid=0x0000ffffb418d6b0 nid=0x350010 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #9 daemon prio=9 os_prio=0 cpu=425.52ms elapsed=120.26s tid=0x0000ffffb418ec10 nid=0x350011 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #10 daemon prio=9 os_prio=0 cpu=0.12ms elapsed=120.25s tid=0x0000ffffb41980a0 nid=0x350012 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Notification Thread" #11 daemon prio=9 os_prio=0 cpu=0.10ms elapsed=120.25s tid=0x0000ffffb41a02a0 nid=0x350013 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #12 daemon prio=8 os_prio=0 cpu=0.43ms elapsed=120.25s tid=0x0000ffffb41a3700 nid=0x350015 in Object.wait()  [0x0000ffff6f00d000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.9/Native Method)
        - waiting on <0x00000007097e27b0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@17.0.9/ReferenceQueue.java:155)
        - locked <0x00000007097e27b0> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@17.0.9/CleanerImpl.java:140)
        at java.lang.Thread.run(java.base@17.0.9/Thread.java:840)
        at jdk.internal.misc.InnocuousThread.run(java.base@17.0.9/InnocuousThread.java:162)

"MainThread" #14 prio=5 os_prio=0 cpu=638.63ms elapsed=120.21s tid=0x0000ffffb41c9e50 nid=0x350016 runnable  [0x0000ffff6ee0d000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.Net.connect0(java.base@17.0.9/Native Method)
        at sun.nio.ch.Net.connect(java.base@17.0.9/Net.java:579)
        at sun.nio.ch.Net.connect(java.base@17.0.9/Net.java:568)
        at sun.nio.ch.NioSocketImpl.connect(java.base@17.0.9/NioSocketImpl.java:593)
        at java.net.Socket.connect(java.base@17.0.9/Socket.java:633)
        at java.net.Socket.connect(java.base@17.0.9/Socket.java:583)
        at sun.net.NetworkClient.doConnect(java.base@17.0.9/NetworkClient.java:183)
        at sun.net.www.http.HttpClient.openServer(java.base@17.0.9/HttpClient.java:533)
        at sun.net.www.http.HttpClient.openServer(java.base@17.0.9/HttpClient.java:638)
        at sun.net.www.http.HttpClient.<init>(java.base@17.0.9/HttpClient.java:281)
        at sun.net.www.http.HttpClient.New(java.base@17.0.9/HttpClient.java:386)
        at sun.net.www.http.HttpClient.New(java.base@17.0.9/HttpClient.java:408)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(java.base@17.0.9/HttpURLConnection.java:1309)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(java.base@17.0.9/HttpURLConnection.java:1242)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(java.base@17.0.9/HttpURLConnection.java:1128)
        at sun.net.www.protocol.http.HttpURLConnection.connect(java.base@17.0.9/HttpURLConnection.java:1057)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(java.base@17.0.9/HttpURLConnection.java:1665)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(java.base@17.0.9/HttpURLConnection.java:1589)
        at java.net.HttpURLConnection.getResponseCode(java.base@17.0.9/HttpURLConnection.java:529)
        at sun.security.provider.certpath.OCSP.getOCSPBytes(java.base@17.0.9/OCSP.java:273)
        at sun.security.provider.certpath.OCSP.check(java.base@17.0.9/OCSP.java:195)
        at sun.security.provider.certpath.RevocationChecker.checkOCSP(java.base@17.0.9/RevocationChecker.java:785)
        at sun.security.provider.certpath.RevocationChecker.check(java.base@17.0.9/RevocationChecker.java:369)
        at sun.security.provider.certpath.RevocationChecker.check(java.base@17.0.9/RevocationChecker.java:343)
        at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(java.base@17.0.9/PKIXMasterCertPathValidator.java:125)
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(java.base@17.0.9/PKIXCertPathValidator.java:224)
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(java.base@17.0.9/PKIXCertPathValidator.java:144)
        at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(java.base@17.0.9/PKIXCertPathValidator.java:83)
        at java.security.cert.CertPathValidator.validate(java.base@17.0.9/CertPathValidator.java:309)
        at ValidatePathWithParams.doCertPathValidate(ValidatePathWithParams.java:288)
        at ValidatePathWithParams.validate(ValidatePathWithParams.java:142)
        at CertignaCAs.runTest(CertignaRoots.java:289)
        at CertignaRoots.main(CertignaRoots.java:252)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.9/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.9/NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.9/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@17.0.9/Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(java.base@17.0.9/Thread.java:840)

"Attach Listener" #15 daemon prio=9 os_prio=0 cpu=0.26ms elapsed=0.10s tid=0x0000ffff64000cd0 nid=0x3504bc waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=4.89ms elapsed=120.27s tid=0x0000ffffb417aba0 nid=0x35000a runnable

"GC Thread#0" os_prio=0 cpu=4.51ms elapsed=120.28s tid=0x0000ffffb408fbd0 nid=0x350005 runnable

"GC Thread#1" os_prio=0 cpu=9.65ms elapsed=88.22s tid=0x0000ffff70004f10 nid=0x35014d runnable

"GC Thread#2" os_prio=0 cpu=7.70ms elapsed=88.22s tid=0x0000ffff70005960 nid=0x35014e runnable

"GC Thread#3" os_prio=0 cpu=9.56ms elapsed=88.22s tid=0x0000ffff700063b0 nid=0x35014f runnable

"G1 Main Marker" os_prio=0 cpu=0.10ms elapsed=120.28s tid=0x0000ffffb40a06f0 nid=0x350006 runnable

"G1 Conc#0" os_prio=0 cpu=0.07ms elapsed=120.28s tid=0x0000ffffb40a1670 nid=0x350007 runnable

"G1 Refine#0" os_prio=0 cpu=1.44ms elapsed=120.28s tid=0x0000ffffb4144800 nid=0x350008 runnable

"G1 Refine#1" os_prio=0 cpu=0.58ms elapsed=88.22s tid=0x0000ffff7c000cd0 nid=0x350150 runnable

"G1 Service" os_prio=0 cpu=10.67ms elapsed=120.28s tid=0x0000ffffb4145710 nid=0x350009 runnable

"VM Periodic Task Thread" os_prio=0 cpu=29.32ms elapsed=120.25s tid=0x0000ffffb41a1c10 nid=0x350014 waiting on condition

JNI global refs: 15, weak refs: 0

--- Timeout information end.
elapsed time (seconds): 120.322


```

【版本信息】
```
[root@VM20210305-10 d17]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;java -version; java -Xinternalversion
Linux VM20210305-10 4.19.91-26.an8.aarch64 #1 SMP Tue May 24 13:14:10 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
NAME="Anolis OS"
VERSION="8.6"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.6"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.6"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

              total        used        free      shared  buff/cache   available
Mem:           15Gi       403Mi       2.1Gi       0.0Ki        12Gi        14Gi
Swap:            0B          0B          0B
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per cluster: 4
Socket(s):           2
Cluster(s):          1
NUMA node(s):        1
Vendor ID:           HiSilicon
BIOS Vendor ID:      Alibaba Cloud
Model:               0
Model name:          Kunpeng-920
BIOS Model name:     virt-rhel7.6.0
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.8.0.9+7-GA (build 17.0.9+7)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.8.0.9+7-GA (build 17.0.9+7, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.9+7) for linux-aarch64 JRE (17.0.9+7), built on Oct 17 2023 00:00:00 by "dragonwell" with gcc 10.3.0
[root@VM20210305-10 d17]# echo $native $args $test
-nativepath:./test-image/hotspot/jtreg/native -Xmixed -ea -esa jdk-repo/test/jdk/security/infra/java/security/cert/CertPathValidator/certification/CertignaRoots.java


```

**Comment by sendaoYan** [comment]
jdk17u-dev 已经合入  https://github.com/openjdk/jdk17u-dev/pull/1805
