### ISSUE TITLE
ajdk11 -【regress】gtest/GTestWrapper.java用例报错

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-releng/dragonwell-adoptium#26]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148193?tab=1

```log
[----------] Global test environment tear-down
[==========] 506 tests from 97 test cases ran. (15591 ms total)
[  PASSED  ] 505 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] VMStructs.VMTypes_duplicates_test

 1 FAILED TEST
];
 stderr: [ERROR: RUN_ALL_TESTS() failed. Error 1
]
 exitValue = 2

java.lang.RuntimeException: Expected to get exit value of [0]

	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
	at GTestWrapper.main(GTestWrapper.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:991)


./test/hotspot/gtest/runtime/test_vmStructs.cpp:60: Failure
Expected: (VMStructs::localHotSpotVMTypes[i].typeName) != (VMStructs::localHotSpotVMTypes[j].typeName), actual: "NegVFNode" vs "NegVFNode"
Duplicate entries on indexes 484 and 487
./test/hotspot/gtest/runtime/test_vmStructs.cpp:60: Failure
Expected: (VMStructs::localHotSpotVMTypes[i].typeName) != (VMStructs::localHotSpotVMTypes[j].typeName), actual: "NegVDNode" vs "NegVDNode"
Duplicate entries on indexes 485 and 488
./test/hotspot/gtest/runtime/test_vmStructs.cpp:60: Failure
Expected: (VMStructs::localHotSpotVMTypes[i].typeName) != (VMStructs::localHotSpotVMTypes[j].typeName), actual: "MinReductionVNode" vs "MinReductionVNode"
Duplicate entries on indexes 509 and 520
./test/hotspot/gtest/runtime/test_vmStructs.cpp:60: Failure
Expected: (VMStructs::localHotSpotVMTypes[i].typeName) != (VMStructs::localHotSpotVMTypes[j].typeName), actual: "MaxReductionVNode" vs "MaxReductionVNode"
Duplicate entries on indexes 510 and 519
```

[GTestWrapper.jtr.log](https://github.com/dragonwell-releng/dragonwell-adoptium/files/10820441/GTestWrapper.jtr.log)

![image](https://user-images.githubusercontent.com/24123821/221085953-363be90f-1a47-42f0-b8d5-460f28b195af.png)

dragonwell11正常：

![image](https://user-images.githubusercontent.com/24123821/221085985-eca97e03-f053-4497-bd8a-785836190fbf.png)

**Comment by zhengxiaolinX** [comment]
Fixed.

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14142458
