### ISSUE TITLE
【dragonwell21】在x64/aarch64平台gtest下多个用例在默认选项下: not found library 

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#267]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/244256?tab=2
【环境准备】
```
wget -O binary.tar.gz https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-59/OpenJDK21U-jdk_x64_linux_dragonwell_2023-11-02-02-07.tar.gz
wget -O test-image.tar.gz https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-59/OpenJDK21U-testimage_x64_linux_dragonwell_2023-11-02-02-07.tar.gz
wget -O jtreg.zip https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg-7.3.1.zip
git clone https://github.com/dragonwell-project/dragonwell21.git -b wip_dragonwell_standard_merge_branch jdk-repo

mkdir binary-download 
tar xzvf binary.tar.gz -C binary-download ; cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME &&cd -
make test-image ; tar xzvf test-image.tar.gz -C test-image
unzip jtreg.zip; cd jtreg ; export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH ; cd -

test=\
jdk-repo/test/hotspot/jtreg/gtest/GTestWrapper.java

args='-Xmixed'
native='-nativepath:./test-image/hotspot/jtreg/native'
jtreg -w tmp -nr -v:fail,error $native  $args $test 
```

类似用例:
gtest/GTestWrapper.java
gtest/LargePageGtests.java#use-large-pages
gtest/LargePageGtests.java#use-large-pages-1G
gtest/LargePageGtests.java#use-large-pages-sysV
gtest/MetaspaceGtests.java#balanced-no-ccs
gtest/AsyncLogGtest.java
gtest/NMTGtests.java#nmt-detail
gtest/NMTGtests.java#nmt-off
gtest/NMTGtests.java#nmt-summary
gtest/NativeHeapTrimmerGtest.java

【对比测试】

dragonwell21 release无
 
```
无
```

temurin21 同样问题
wget https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.1%2B12/OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz
```
[root@VM20190228-137 t21]# java -version; java -Xinternalversion
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)
OpenJDK 64-Bit Server VM (21.0.1+12-LTS) for linux-amd64 JRE (21.0.1+12-LTS), built on 2023-10-17T00:00:00Z by "admin" with gcc 11.2.0

```

【用例日志】

Tone完整日志:
```
--------------------------------------------------
TEST: gtest/NativeHeapTrimmerGtest.java
TEST JDK: /tmp/tone/run/jtreg/binary-download/dragonwell-21.0.1.0.1+12-GA

ACTION: build -- Passed. Build successful
REASON: Named class compiled on demand
TIME:   7.589 seconds
messages:
command: build GTestWrapper
reason: Named class compiled on demand
started: Wed Nov 08 18:12:51 CST 2023
Test directory:
  compile: GTestWrapper
finished: Wed Nov 08 18:12:58 CST 2023
elapsed time (seconds): 7.589

ACTION: compile -- Passed. Compilation successful
REASON: .class file out of date or does not exist
TIME:   7.588 seconds
messages:
command: compile /tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/gtest/GTestWrapper.java
reason: .class file out of date or does not exist
started: Wed Nov 08 18:12:51 CST 2023
Additional options from @modules: --add-modules java.base,java.xml --add-exports java.base/jdk.internal.misc=ALL-UNNAMED
Mode: othervm
finished: Wed Nov 08 18:12:58 CST 2023
elapsed time (seconds): 7.588
configuration:
javac compilation environment
  add modules: java.base java.xml          
  add exports: java.base/jdk.internal.misc ALL-UNNAMED
  source path: /tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/gtest 
               /tmp/tone/run/jtreg/jdk-repo/test/lib 
  class path:  /tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/gtest 
               /tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/48/gtest/NativeHeapTrimmerGtest.d 
               /tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/48/test/lib 

rerun:
cd /tmp/tone/run/jtreg/jt-work/hotspot_jtreg/gtest/NativeHeapTrimmerGtest && \
DISPLAY=:7 \
HOME=/home/testUserForTone \
LANG=C \
LC_CTYPE=C.UTF-8 \
LD_LIBRARY_PATH= \
PATH=/bin:/usr/bin:/usr/sbin \
TEST_IMAGE_DIR=/tmp/tone/run/jtreg/test-images/dragonwell-21.0.1.0.1+12-GA-test-image \
    /tmp/tone/run/jtreg/binary-download/dragonwell-21.0.1.0.1+12-GA/bin/javac \
        -J-Djdk.lang.processReaperUseDefaultStackSize=true \
        -J-Dtest.wisp.socketAddress=www.alibabacloud.com \
        -J-Xmixed \
        -J-ea \
        -J-esa \
        -J-Dtest.vm.opts='-Djdk.lang.processReaperUseDefaultStackSize=true -Dtest.wisp.socketAddress=www.alibabacloud.com -Xmixed -ea -esa' \
        -J-Dtest.tool.vm.opts='-J-Djdk.lang.processReaperUseDefaultStackSize=true -J-Dtest.wisp.socketAddress=www.alibabacloud.com -J-Xmixed -J-ea -J-esa' \
        -J-Dtest.compiler.opts= \
        -J-Dtest.java.opts= \
        -J-Dtest.jdk=/tmp/tone/run/jtreg/binary-download/dragonwell-21.0.1.0.1+12-GA \
        -J-Dcompile.jdk=/tmp/tone/run/jtreg/binary-download/dragonwell-21.0.1.0.1+12-GA \
        -J-Dtest.timeout.factor=4.0 \
        -J-Dtest.nativepath=/tmp/tone/run/jtreg/test-images/dragonwell-21.0.1.0.1+12-GA-test-image/hotspot/jtreg/native \
        -J-Dtest.root=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg \
        -J-Dtest.name=gtest/NativeHeapTrimmerGtest.java \
        -J-Dtest.file=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/gtest/NativeHeapTrimmerGtest.java \
        -J-Dtest.src=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/gtest \
        -J-Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/gtest:/tmp/tone/run/jtreg/jdk-repo/test/lib \
        -J-Dtest.classes=/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/48/gtest/NativeHeapTrimmerGtest.d \
        -J-Dtest.class.path=/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/48/gtest/NativeHeapTrimmerGtest.d:/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/48/test/lib \
        -J-Dtest.modules='java.base/jdk.internal.misc java.xml' \
        @/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/gtest/NativeHeapTrimmerGtest.d/compile.0.jta
STDOUT:
STDERR:
Note: /tmp/tone/run/jtreg/jdk-repo/test/lib/jdk/test/lib/process/ProcessTools.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Error: TESTBUG: the library has not been found in /tmp/tone/run/jtreg/test-images/dragonwell-21.0.1.0.1+12-GA-test-image/hotspot/jtreg/native. Did you forget to use --with-gtest to configure?
REASON: User specified action: run main/native GTestWrapper --gtest_filter=os.trim* -Xlog:trimnative -XX:+UnlockExperimentalVMOptions -XX:TrimNativeHeapInterval=100 
TIME:   0.677 seconds
messages:
command: main GTestWrapper --gtest_filter=os.trim* -Xlog:trimnative -XX:+UnlockExperimentalVMOptions -XX:TrimNativeHeapInterval=100
reason: User specified action: run main/native GTestWrapper --gtest_filter=os.trim* -Xlog:trimnative -XX:+UnlockExperimentalVMOptions -XX:TrimNativeHeapInterval=100 
started: Wed Nov 08 18:12:58 CST 2023
Mode: othervm
Additional options from @modules: --add-modules java.base,java.xml --add-exports java.base/jdk.internal.misc=ALL-UNNAMED
finished: Wed Nov 08 18:12:59 CST 2023
elapsed time (seconds): 0.677
configuration:
Boot Layer
  add modules: java.base java.xml          
  add exports: java.base/jdk.internal.misc ALL-UNNAMED

STDOUT:
STDERR:
java.lang.Error: TESTBUG: the library has not been found in /tmp/tone/run/jtreg/test-images/dragonwell-21.0.1.0.1+12-GA-test-image/hotspot/jtreg/native. Did you forget to use --with-gtest to configure?
	at GTestWrapper.main(GTestWrapper.java:62)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1583)

JavaTest Message: Test threw exception: java.lang.Error: TESTBUG: the library has not been found in /tmp/tone/run/jtreg/test-images/dragonwell-21.0.1.0.1+12-GA-test-image/hotspot/jtreg/native. Did you forget to use --with-gtest to configure?
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.Error: TESTBUG: the library has not been found in /tmp/tone/run/jtreg/test-images/dragonwell-21.0.1.0.1+12-GA-test-image/hotspot/jtreg/native. Did you forget to use --with-gtest to configure?


```

【版本信息】
```
[root@VM20190228-137 d21]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;java -version; java -Xinternalversion
Linux VM20190228-137 5.10.134-14.al8.x86_64 #1 SMP Thu Apr 27 16:46:29 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:           15Gi       618Mi       446Mi       778Mi        14Gi        13Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
BIOS Vendor ID:      Alibaba Cloud
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
BIOS Model name:     pc-i440fx-2.1
Stepping:            4
CPU MHz:             2500.012
BogoMIPS:            5000.02
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0-3
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-21.0.1.0.1+12-GA (build 21.0.1)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-21.0.1.0.1+12-GA (build 21.0.1, mixed mode, sharing)
OpenJDK 64-Bit Server VM (21.0.1) for linux-amd64 JRE (21.0.1), built on 2023-10-17T00:00:00Z by "dragonwell" with gcc 11.2.0

```

**Comment by sendaoYan** [comment]
构建的时候，configure需要配置--with-gtest=/home/yansendao.ysd/git/googletest-1.13.0
git clone -b v1.13.0 git@github.com:google/googletest.git googletest-1.13.0

**Comment by sendaoYan** [comment]
本地运行结果

**Comment by owanqian** [comment]
http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-x64-dragonwell/21/artifact/workspace/target/OpenJDK21U-jdk_x64_linux_dragonwell_2023-11-20-03-28.tar.gz  验证通过. 
![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/32159229/25e4724b-c4e0-4efe-8da6-b2f641016eae)

**Comment by owanqian** [comment]
http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-aarch64-dragonwell/5/artifact/workspace/target/OpenJDK21U-jdk_aarch64_linux_dragonwell_2023-11-20-03-28.tar.gz  验证通过 
![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/32159229/2c0aa708-6e83-466c-bfad-355ff2b9fcb1)
