### ISSUE TITLE
ajdk11 - 自研metaspace-dump/HeapDumpPathTest.java用例失败

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-releng/dragonwell-adoptium#27]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148193?tab=1

```log
Command line: [/tmp/tone/run/jtreg/binary-download/jdk-11.0.17.16+/bin/java -cp /tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/32/metaspace-dump/HeapDumpPathTest.d:/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/metaspace-dump:/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/32/test/lib:/tmp/tone/run/jtreg/jdk-repo/test/lib:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar -Xms10m -Xmx10m -Xmn5m -XX:+HeapDumpBeforeFullGC -XX:+HeapDumpAfterFullGC -XX:+HeapDumpOnOutOfMemoryError OOM ]
[2023-02-22T12:22:54.096133Z] Gathering output for process 321122
STDERR:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by HeapDumpPathTest (file:/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/32/metaspace-dump/HeapDumpPathTest.d/) to field java.lang.ProcessImpl.pid
WARNING: Please consider reporting this to the maintainers of HeapDumpPathTest
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.RuntimeException: assertTrue: expected true, was false
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
	at jdk.test.lib.Asserts.assertTrue(Asserts.java:472)
	at HeapDumpPathTest.checkFile(HeapDumpPathTest.java:82)
	at HeapDumpPathTest.main(HeapDumpPathTest.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:991)
```

![image](https://user-images.githubusercontent.com/24123821/221086727-2028df03-19e1-4f5b-8e9b-6c5d2f462905.png)

**Comment by sendaoYan** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/59321867# 《[ajdk11]自研metaspace-dump/HeapDumpPathTest.java用例报错java.lang.RuntimeException: assertTrue: expected true, was false》
