### ISSUE TITLE
ajdk11 - 自研runtime/CDSCompressedKPtrs/CDSCompressedKPtrsError.java报错

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-releng/dragonwell-adoptium#28]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148193?tab=1

```log
Command line: [/tmp/tone/run/jtreg/binary-download/jdk-11.0.17.16+/bin/java -cp /tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/42/runtime/CDSCompressedKPtrs/CDSCompressedKPtrsError.d:/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/runtime/CDSCompressedKPtrs:/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/42/test/lib:/tmp/tone/run/jtreg/jdk-repo/test/lib:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar -XX:-UseCompressedOops -XX:+UseCompressedClassPointers -XX:+UnlockDiagnosticVMOptions -XX:SharedArchiveFile=./CDSCompressedKPtrsErrorBad1.jsa -Xshare:dump ]
[2023-02-22T12:24:03.572295Z] Gathering output for process 357106
[2023-02-22T12:24:04.334151Z] Waiting for completion for process 357106
[2023-02-22T12:24:04.334300Z] Waiting for completion finished for process 357106
STDERR:
 stdout: [Error occurred during initialization of VM
Unable to use shared archive.
];
 stderr: [An error has occurred while processing the shared archive file.
Unable to use shared archive.
The saved state of UseCompressedOops and UseCompressedClassPointers is different from runtime, CDS will be disabled.
]
 exitValue = 1

 stdout: [Allocated shared space: 3221225472 bytes at 0x0000000800000000
Loading classes to share ...
Loading classes to share: done.
Rewriting and linking classes ...
Rewriting and linking classes: done
Number of classes 1257
    instance classes   =  1196
    obj array classes  =    53
    type array classes =     8
Updating ConstMethods ... done. 
Removing unshareable information ... done. 
Scanning all metaspace objects ... 
Allocating RW objects ... 
Allocating RO objects ... 
Relocating embedded pointers ... 
Relocating external roots ... 
Dumping symbol table ...
Relocating SystemDictionary::_well_known_klasses[] ... 
Removing java_mirror ... done. 
mc  space:      8704 [  0.1% of total] out of     12288 bytes [ 70.8% used] at 0x0000000800000000
rw  space:   4135976 [ 36.0% of total] out of   4136960 bytes [100.0% used] at 0x0000000800003000
ro  space:   7337208 [ 63.8% of total] out of   7340032 bytes [100.0% used] at 0x00000008003f5000
md  space:      2560 [  0.0% of total] out of      4096 bytes [ 62.5% used] at 0x0000000800af5000
total    :  11484448 [100.0% of total] out of  11493376 bytes [ 99.9% used]
];
 stderr: [OpenJDK 64-Bit Server VM warning: UseCompressedClassPointers requires UseCompressedOops
]
 exitValue = 0

java.lang.RuntimeException: 'Cannot dump shared archive' missing from stdout/stderr 

	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:163)
	at CDSCompressedKPtrsError.main(CDSCompressedKPtrsError.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:991)

JavaTest Message: Test threw exception: java.lang.RuntimeException: 'Cannot dump shared archive' missing from stdout/stderr 

JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: 'Cannot dump shared archive' missing from stdout/stderr
```

dragonwell11没有这个用例

**Comment by zhengxiaolinX** [comment]
已修复，在 WIP 上

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14143416
