### ISSUE TITLE
【dragonwell17】rpm包运行sun/nio/cs/mapping/CoderTest.java失败:GB18030 字符集有错误.

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#291]
x86: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/248397?tab=1

【环境准备】
```
BINARY_URL=https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/koji/20231120-141154-241-#9-linux.x86_64.release.fake_branch-java-17-alibaba-dragonwell-17.0.9.0.10.9.1.al8.jdk-rpm.tar.gz
TEST_IMAGE=oss://compiler-ci-bucket/dragonwell17/20231114-002504-781-#153-linux.x86_64.release.standard-effce46066d79b05140bee59cff5a8591bf9f1fe.test-image.tar.gz
git clone https://github.com/dragonwell-project/dragonwell17.git  jdk-repo
test=jdk-repo/test/jdk/sun/nio/cs/mapping/CoderTest.java
jtreg -va -nr -w tmp $test
```

【对比测试】

dragonwell17 tar版本同样问题.
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/17.0.9.0.10%2B9/Alibaba_Dragonwell_Standard_17.0.9.0.10%2B9_x64_linux.tar.gz\

```
[root@iZbp1hmgsldsm4l82drivdZ bin]# ./java -version; ./java -Xinternalversion
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.9.0.10+9-GA (build 17.0.9+9)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.9.0.10+9-GA (build 17.0.9+9, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.9+9) for linux-amd64 JRE (17.0.9+9), built on Oct 17 2023 00:00:00 by "dragonwell" with gcc 7.5.0

```
temurin17 同样问题
wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.9%2B9/OpenJDK17U-jdk_x64_linux_hotspot_17.0.9_9.tar.gz
```
[root@iZbp1eqvwk9o1gtluk2ijpZ bin]# ./java -version; ./java -Xinternalversion
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.9+9) for linux-amd64 JRE (17.0.9+9), built on Oct 17 2023 00:00:00 by "admin" with gcc 10.3.0
```
【用例日志】

```
GB18030 (GB18030)
  1 byte/char
    decode
    decode (direct)
    encode
    encode (direct)
  2 bytes/char
    decode
      Error: a6d9 --> U+fe10, expected U+e78d
      Error: a6da --> U+fe12, expected U+e78e
      Error: a6db --> U+fe11, expected U+e78f
      Error: a6dc --> U+fe13, expected U+e790
      Error: a6dd --> U+fe14, expected U+e791
      Error: a6de --> U+fe15, expected U+e792
      Error: a6df --> U+fe16, expected U+e793
      Error: a6ec --> U+fe17, expected U+e794
      Error: a6ed --> U+fe18, expected U+e795
      Error: a6f3 --> U+fe19, expected U+e796
      Too many errors, giving up
    decode (direct)
      Error: a6d9 --> U+fe10, expected U+e78d
      Error: a6da --> U+fe12, expected U+e78e
      Error: a6db --> U+fe11, expected U+e78f
      Error: a6dc --> U+fe13, expected U+e790
      Error: a6dd --> U+fe14, expected U+e791
      Error: a6de --> U+fe15, expected U+e792
      Error: a6df --> U+fe16, expected U+e793
      Error: a6ec --> U+fe17, expected U+e794
      Error: a6ed --> U+fe18, expected U+e795
      Error: a6f3 --> U+fe19, expected U+e796
      Too many errors, giving up
    encode
      Error: U+e78d --> 8431, expected a6d9
      Error: U+e78e --> 8236, expected a6da
      Error: U+e78f --> 8431, expected a6db
      Error: U+e790 --> 8238, expected a6dc
      Error: U+e791 --> 8431, expected a6dd
      Error: U+e792 --> 8237, expected a6de
      Error: U+e793 --> 8431, expected a6df
      Error: U+e794 --> 8239, expected a6ec
      Error: U+e795 --> 8431, expected a6ed
      Error: U+e796 --> 8330, expected a6f3
      Too many errors, giving up
    encode (direct)
      Error: U+e78d --> 8431, expected a6d9
      Error: U+e78e --> 8236, expected a6da
      Error: U+e78f --> 8431, expected a6db
      Error: U+e790 --> 8238, expected a6dc
      Error: U+e791 --> 8431, expected a6dd
      Error: U+e792 --> 8237, expected a6de
      Error: U+e793 --> 8431, expected a6df
      Error: U+e794 --> 8239, expected a6ec
      Error: U+e795 --> 8431, expected a6ed
      Error: U+e796 --> 8330, expected a6f3
      Too many errors, giving up
  3 bytes/char
    decode
    decode (direct)
    encode
    encode (direct)
  4 bytes/char
    decode
      Error: 8135f437 --> U+e7c7, expected U+1e3f
      Error: 82359037 --> U+e81e, expected U+9fb4
      Error: 82359038 --> U+e826, expected U+9fb5
      Error: 82359039 --> U+e82b, expected U+9fb6
      Error: 82359130 --> U+e82c, expected U+9fb7
      Error: 82359131 --> U+e832, expected U+9fb8
      Error: 82359132 --> U+e843, expected U+9fb9
      Error: 82359133 --> U+e854, expected U+9fba
      Error: 82359134 --> U+e864, expected U+9fbb
      Error: 84318236 --> U+e78d, expected U+fe10
      Too many errors, giving up
    decode (direct)
      Error: 8135f437 --> U+e7c7, expected U+1e3f
      Error: 82359037 --> U+e81e, expected U+9fb4
      Error: 82359038 --> U+e826, expected U+9fb5
      Error: 82359039 --> U+e82b, expected U+9fb6
      Error: 82359130 --> U+e82c, expected U+9fb7
      Error: 82359131 --> U+e832, expected U+9fb8
      Error: 82359132 --> U+e843, expected U+9fb9
      Error: 82359133 --> U+e854, expected U+9fba
      Error: 82359134 --> U+e864, expected U+9fbb
      Error: 84318236 --> U+e78d, expected U+fe10
      Too many errors, giving up
    encode
      Error: U+1e3f --> a8bc8135, expected 8135f437
      Error: U+1e40 --> f4388135, expected 8135f438
      Error: U+1e41 --> f4398135, expected 8135f439
      Error: U+1e42 --> f5308135, expected 8135f530
      Error: U+1e43 --> f5318135, expected 8135f531
      Error: U+1e44 --> f5328135, expected 8135f532
      Error: U+1e45 --> f5338135, expected 8135f533
      Error: U+1e46 --> f5348135, expected 8135f534
      Error: U+1e47 --> f5358135, expected 8135f535
      Error: U+1e48 --> f5368135, expected 8135f536
      Too many errors, giving up
    encode (direct)
      Error: U+1e3f --> a8bc8135, expected 8135f437
      Error: U+1e40 --> f4388135, expected 8135f438
      Error: U+1e41 --> f4398135, expected 8135f439
      Error: U+1e42 --> f5308135, expected 8135f530
      Error: U+1e43 --> f5318135, expected 8135f531
      Error: U+1e44 --> f5328135, expected 8135f532
      Error: U+1e45 --> f5338135, expected 8135f533
      Error: U+1e46 --> f5348135, expected 8135f534
      Error: U+1e47 --> f5358135, expected 8135f535
      Error: U+1e48 --> f5368135, expected 8135f536
      Too many errors, giving up
STDERR:
java.lang.Exception: Errors detected in 1 charset
        at CoderTest.main(CoderTest.java:517)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:840)

JavaTest Message: Test threw exception: java.lang.Exception: Errors detected in 1 charset
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.Exception: Errors detected in 1 charset

```

【版本信息】
```
[root@iZbp1hmgsldsm4l82drivdZ jtreg]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;java -version; java -Xinternalversion
Linux iZbp1hmgsldsm4l82drivdZ 5.10.134-15.al8.x86_64 #1 SMP Thu Jul 20 00:44:04 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:           61Gi       593Mi        52Gi       3.0Mi       8.1Gi        60Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  2
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
BIOS Vendor ID:      Alibaba Cloud
CPU family:          6
Model:               143
Model name:          Intel(R) Xeon(R) Platinum 8475B
BIOS Model name:     pc-i440fx-2.1
Stepping:            8
CPU MHz:             3198.741
CPU max MHz:         3800.0000
CPU min MHz:         800.0000
BogoMIPS:            5400.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            2048K
openjdk version "17.0.9.9" 2023-11-17
OpenJDK Runtime Environment (Alibaba Dragonwell) (build 17.0.9.9+9)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell) (build 17.0.9.9+9, mixed mode)
OpenJDK 64-Bit Server VM (17.0.9.9+9) for linux-amd64 JRE (17.0.9.9+9), built on Nov 17 2023 03:05:05 by "mockbuild" with gcc 10.2.1 20200825 (Alibaba 10.2.1-3.5 2.32)

```

**Comment by owanqian** [comment]
无效问题,关闭.https://tone.aliyun-inc.com/ws/xesljfzh/test_result/250332
