### ISSUE TITLE
【dragonwell17】x86_64 rpm包运行jdk/tools/jlink/JLinkReproducibleTest.java概率性失败.

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#295]
x86: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/248397?tab=1

【环境准备】
```
BINARY_URL=https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/koji/20231120-141154-241-#9-linux.x86_64.release.fake_branch-java-17-alibaba-dragonwell-17.0.9.0.10.9.1.al8.jdk-rpm.tar.gz
TEST_IMAGE=oss://compiler-ci-bucket/dragonwell17/20231114-002504-781-#153-linux.x86_64.release.standard-effce46066d79b05140bee59cff5a8591bf9f1fe.test-image.tar.gz
git clone https://github.com/dragonwell-project/dragonwell17.git  jdk-repo
test=jdk-repo/test/jdk/tools/jlink/JLinkReproducibleTest.java 

rm -rf jt-work; mkdir jt-work ; nproc=`nproc`
nohup time seq 10000 | xargs -i -n 1 -I {} -P $nproc bash -c "jtreg -w tmp -nr -v:fail,error $native  $args $test &> jt-work/test_{}" &

```
【对比测试】

极小概率能复现15/10000

dragonwell17 tar版本未复现出此错误(一万次未出现).
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/17.0.9.0.10%2B9/Alibaba_Dragonwell_Standard_17.0.9.0.10%2B9_x64_linux.tar.gz

```
[root@iZbp1hmgsldsm4l82drivdZ bin]# ./java -version; ./java -Xinternalversion
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.9.0.10+9-GA (build 17.0.9+9)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.9.0.10+9-GA (build 17.0.9+9, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.9+9) for linux-amd64 JRE (17.0.9+9), built on Oct 17 2023 00:00:00 by "dragonwell" with gcc 7.5.0

```

【用例日志】

```
STDOUT:
[2023-11-22T06:27:29.160328916Z] Gathering output for process 4056454
[2023-11-22T06:27:30.293198972Z] Waiting for completion for process 4056454
[2023-11-22T06:27:30.293337160Z] Waiting for completion finished for process 4056454
Output and diagnostic info for process 4056454 was saved into 'pid-4056454-output.log'
[2023-11-22T06:27:30.294353349Z] Waiting for completion for process 4056454
[2023-11-22T06:27:30.294452625Z] Waiting for completion finished for process 4056454
[2023-11-22T06:27:30.324956643Z] Gathering output for process 4057077
[2023-11-22T06:27:38.169370513Z] Waiting for completion for process 4057077
[2023-11-22T06:27:38.169551666Z] Waiting for completion finished for process 4057077
Output and diagnostic info for process 4057077 was saved into 'pid-4057077-output.log'
[2023-11-22T06:27:38.170029234Z] Waiting for completion for process 4057077
[2023-11-22T06:27:38.170091479Z] Waiting for completion finished for process 4057077
[2023-11-22T06:27:38.196234070Z] Gathering output for process 4061752
[2023-11-22T06:27:45.572926892Z] Waiting for completion for process 4061752
[2023-11-22T06:27:45.573070121Z] Waiting for completion finished for process 4061752
Output and diagnostic info for process 4061752 was saved into 'pid-4061752-output.log'
[2023-11-22T06:27:45.573607716Z] Waiting for completion for process 4061752
[2023-11-22T06:27:45.573688642Z] Waiting for completion finished for process 4061752
STDERR:
java.lang.RuntimeException: assertEquals: expected -1 to equal 371779
        at jdk.test.lib.Asserts.fail(Asserts.java:594)
        at jdk.test.lib.Asserts.assertEquals(Asserts.java:205)
        at jdk.test.lib.Asserts.assertEquals(Asserts.java:189)
        at JLinkReproducibleTest.main(JLinkReproducibleTest.java:115)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:840)

JavaTest Message: Test threw exception: java.lang.RuntimeException: assertEquals: expected -1 to equal 371779
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: assertEquals: expected -1 to equal 371779
rerun:
cd /var/tmp/tone/run/jtreg/tmp/scratch_1 && \
DISPLAY=localhost:10.0 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/var/tmp/tone/run/jtreg/tmp/classes/tools/jlink/JLinkReproducibleTest.d:/var/tmp/tone/run/jtreg/jdk-repo/test/jdk/tools/jlink:/var/tmp/tone/run/jtreg/tmp/classes/test/lib:/var/tmp/tone/run/jtreg/jdk-repo/test/lib:/var/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/var/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /tmp/tone/run/jtreg/binary-download/usr/lib/jvm/java-17-alibaba-dragonwell-17.0.9.0.10.9-1.al8.x86_64/bin/java \
        -Dtest.vm.opts=-Xmixed \
        -Dtest.tool.vm.opts=-J-Xmixed \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/tmp/tone/run/jtreg/binary-download/usr/lib/jvm/java-17-alibaba-dragonwell-17.0.9.0.10.9-1.al8.x86_64 \
        -Dcompile.jdk=/tmp/tone/run/jtreg/binary-download/usr/lib/jvm/java-17-alibaba-dragonwell-17.0.9.0.10.9-1.al8.x86_64 \
        -Dtest.timeout.factor=1.0 \
        -Dtest.nativepath=/var/tmp/tone/run/jtreg/./test-images/test-image/hotspot/jtreg/native \
        -Dtest.root=/var/tmp/tone/run/jtreg/jdk-repo/test/jdk \
        -Dtest.name=tools/jlink/JLinkReproducibleTest.java \
        -Dtest.file=/var/tmp/tone/run/jtreg/jdk-repo/test/jdk/tools/jlink/JLinkReproducibleTest.java \
        -Dtest.src=/var/tmp/tone/run/jtreg/jdk-repo/test/jdk/tools/jlink \
        -Dtest.src.path=/var/tmp/tone/run/jtreg/jdk-repo/test/jdk/tools/jlink:/var/tmp/tone/run/jtreg/jdk-repo/test/lib \
        -Dtest.classes=/var/tmp/tone/run/jtreg/tmp/classes/tools/jlink/JLinkReproducibleTest.d \
        -Dtest.class.path=/var/tmp/tone/run/jtreg/tmp/classes/tools/jlink/JLinkReproducibleTest.d:/var/tmp/tone/run/jtreg/tmp/classes/test/lib \
        -Xmixed \
        -Djava.library.path=/var/tmp/tone/run/jtreg/./test-images/test-image/hotspot/jtreg/native \
        com.sun.javatest.regtest.agent.MainWrapper /var/tmp/tone/run/jtreg/tmp/tools/jlink/JLinkReproducibleTest.d/driver.0.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: assertEquals: expected -1 to equal 371779

```

【版本信息】
```
[root@iZbp1hmgsldsm4l82drivdZ jtreg]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;java -version; java -Xinternalversion
Linux iZbp1hmgsldsm4l82drivdZ 5.10.134-15.al8.x86_64 #1 SMP Thu Jul 20 00:44:04 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:           61Gi       593Mi        52Gi       3.0Mi       8.1Gi        60Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  2
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
BIOS Vendor ID:      Alibaba Cloud
CPU family:          6
Model:               143
Model name:          Intel(R) Xeon(R) Platinum 8475B
BIOS Model name:     pc-i440fx-2.1
Stepping:            8
CPU MHz:             3198.741
CPU max MHz:         3800.0000
CPU min MHz:         800.0000
BogoMIPS:            5400.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            2048K
openjdk version "17.0.9.9" 2023-11-17
OpenJDK Runtime Environment (Alibaba Dragonwell) (build 17.0.9.9+9)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell) (build 17.0.9.9+9, mixed mode)
OpenJDK 64-Bit Server VM (17.0.9.9+9) for linux-amd64 JRE (17.0.9.9+9), built on Nov 17 2023 03:05:05 by "mockbuild" with gcc 10.2.1 20200825 (Alibaba 10.2.1-3.5 2.32)

```

**Comment by owanqian** [comment]
无效问题,关闭.https://tone.aliyun-inc.com/ws/xesljfzh/test_result/250332
