### ISSUE TITLE
ajdk11 - 【regress】runtime/appcds/ExtraSymbols.java报错

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-releng/dragonwell-adoptium#30]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148193?tab=1

```log
java.lang.RuntimeException: 'Shared symbol table stats -------- base:' missing from stdout/stderr 

	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:163)
	at ExtraSymbols.checkOutput(ExtraSymbols.java:86)
	at ExtraSymbols.main(ExtraSymbols.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:991)
```

![image](https://user-images.githubusercontent.com/24123821/221121412-3d7c4442-e166-4e83-88a6-22f6c0ecc38f.png)

**Comment by sendaoYan** [comment]
如下用例归类为同一类问题：

```log
runtime/appcds/ExtraSymbols.java
runtime/appcds/TestCombinedCompressedFlags.java
runtime/appcds/TestZGCWithCDS.java
runtime/appcds/VerifierTest_1A.java
runtime/appcds/VerifierTest_1B.java
runtime/appcds/VerifierTest_2.java
runtime/appcds/customLoader/ProhibitedPackageNamesTest.java
runtime/appcds/jigsaw/modulepath/ModulePathAndCP.java
runtime/appcds/jigsaw/modulepath/ModulePathAndCP_JFR.java
runtime/appcds/sharedStrings/ExerciseGC.java
runtime/appcds/sharedStrings/FlagCombo.java#id0
runtime/appcds/sharedStrings/IncompatibleOptions.java
runtime/appcds/sharedStrings/InternSharedString.java
runtime/appcds/sharedStrings/LargePages.java
runtime/appcds/sharedStrings/LockSharedStrings.java
runtime/appcds/sharedStrings/SharedStringsBasicPlus.java
runtime/appcds/sharedStrings/SharedStringsWbTest.java
```

**Comment by zhengxiaolinX** [comment]
Done.

**Comment by sendaoYan** [comment]
https://github.com/dragonwell-releng/dragonwell-adoptium/issues/30
