### ISSUE TITLE
ajdk11 -【regress】runtime/execstack/TestCheckJDK.java用例报错

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-releng/dragonwell-adoptium#31]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148193?tab=1

```log
STDOUT:
Library does not have the noexecstack bit set: /tmp/tone/run/jtreg/binary-download/jdk-11.0.17.16+/bin/sat
Library does not have the noexecstack bit set: /tmp/tone/run/jtreg/binary-download/jdk-11.0.17.16+/bin/rssAnalyzer
STDERR:
java.lang.RuntimeException: The tested VM contains libs that don't have the noexecstack bit set. They must be linked with -z,noexecstack.: expected true, was false
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
	at TestCheckJDK.main(TestCheckJDK.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:991)
```

![image](https://user-images.githubusercontent.com/24123821/221124284-24c1edfb-c069-4fcc-b481-720a53d9daf0.png)

dragonwell11正常：

![image](https://user-images.githubusercontent.com/24123821/221124323-e2779403-ded0-495f-8176-534d370139d6.png)

**Comment by zhengxiaolinX** [comment]
sat 是个 shell script，需要确定下修复方案。

**Comment by dzchun** [comment]
最新版本已修复
```
[dongzhichun@CompilerTest-aarch64-5 ajdk11]$ echo $test2
jdk-repo-ajdk11/test/hotspot/jtreg/runtime/execstack/TestCheckJDK.java
[dongzhichun@CompilerTest-aarch64-5 ajdk11]$ j -Xmixed $test2
~/working/tone/ajdk11/bin-ajdk11/jdk-11.0.23.24+0/bin/java
Directory "tmp" not found: creating
--------------------------------------------------
TEST: runtime/execstack/TestCheckJDK.java
TEST RESULT: Passed. Execution successful
--------------------------------------------------
Test results: passed: 1
Results written to /home/dongzhichun/working/tone/ajdk11/tmp

real    0m4.896s
user    0m12.473s
sys     0m1.176s
[dongzhichun@CompilerTest-aarch64-5 ajdk11]$ java -version;java -Xinternalversion
openjdk version "11.0.23.24-AJDK" 2024-08-06
OpenJDK Runtime Environment (Alibaba AJDK) (build 11.0.23.24-AJDK+0-Alibaba)
OpenJDK 64-Bit Server VM (Alibaba AJDK) (build 11.0.23.24-AJDK+0-Alibaba, mixed mode)
OpenJDK 64-Bit Server VM (11.0.23.24-AJDK+0-Alibaba) for linux-aarch64 JRE (11.0.23.24-AJDK+0-Alibaba), built on Aug  6 2024 09:28:43 by "" with gcc 7.3.1 20180303 (Red Hat 7.3.1-5)
[dongzhichun@CompilerTest-aarch64-5 ajdk11]$ uname -a;cat /etc/os-release
Linux CompilerTest-aarch64-5 5.10.134-16.1.al8.aarch64 #1 SMP Thu Dec 7 22:04:51 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
UPDATE_ID="9"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"
```

**Comment by dzchun** [comment]
x64 pass
```
[dongzhichun@CompilerTest-x64-3 ajdk11]$ j -nativepath:images-ajdk11/test-image/hotspot/jtreg/native/ -Djdk.lang.processReaperUseDefaultStackSize=true -Dtest.wisp.socketAddress=www.alibabacloud.com  -Xmixed  -ea -esa jdk-repo-ajdk11/test/hotspot/jtreg/runtime/execstack/TestCheckJDK.java
~/tone/ajdk11/bin-ajdk11/bin/java
Directory "tmp" not found: creating
--------------------------------------------------
TEST: runtime/execstack/TestCheckJDK.java
TEST RESULT: Passed. Execution successful
--------------------------------------------------
Test results: passed: 1
Results written to /home/dongzhichun/tone/ajdk11/tmp

real    0m4.296s
user    0m11.941s
sys     0m0.736s
[dongzhichun@CompilerTest-x64-3 ajdk11]$ java -version;java -Xinternalversion
openjdk version "11.0.23.24-AJDK" 2024-08-10
OpenJDK Runtime Environment (build 11.0.23.24-AJDK+0-Alibaba)
OpenJDK 64-Bit Server VM (build 11.0.23.24-AJDK+0-Alibaba, mixed mode)
OpenJDK 64-Bit Server VM (11.0.23.24-AJDK+0-Alibaba) for linux-amd64 JRE (11.0.23.24-AJDK+0-Alibaba), built on Aug  9 2024 16:47:05 by "" with gcc 7.3.1 20180303 (Red Hat 7.3.1-5)
```

**Comment by sendaoYan** [comment]
![image](https://github.com/user-attachments/assets/3e93b45f-a7ec-402e-bccd-36716814eb51)
