### ISSUE TITLE
ajdk11 - 自研runtime/verifier/TestSigParse.java报错

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-releng/dragonwell-adoptium#32]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148193?tab=1

```log
STDOUT:
Regression test for bug 8219579
STDERR:
java.lang.RuntimeException: Unexpected exception: BadFieldRef has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at TestSigParse.main(TestSigParse.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:991)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Unexpected exception: BadFieldRef has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 55.0
JavaTest Message: shutting down test
```

dragonwell11没有这个用例

![image](https://user-images.githubusercontent.com/24123821/221124933-bb1d81f1-49ba-45f2-b61f-43453b3989de.png)

**Comment by sendaoYan** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/50981632# 《ajdk11 - 自研runtime/verifier/TestSigParse.java报错 #32》
