### ISSUE TITLE
【dragonwell11】extended版本runtime/SharedArchiveFile/ and runtime/appcds/下5个用例fail

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#320]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/257488?tab=2
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/257487
【环境准备】
```
wget -O binary.tar.gz  https://dragonwell.oss-cn-shanghai.aliyuncs.com/11.0.21.18.9-test/Alibaba_Dragonwell_Extended_11.0.21.18.9_x64_linux.tar.gz
wget  -O test-image.tar.gz https://dragonwell.oss-cn-shanghai.aliyuncs.com/11.0.21.18.9-test/Alibaba_Dragonwell_Extended_11.0.21.18.9_x64_linux-testimage.tar.gz

mkdir binary-download && mkdir test-image

tar xzvf binary.tar.gz -C binary-download
tar xzvf test-image.tar.gz -C test-image

cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -

wget -O jtreg.zip http://114.55.64.175:8666/compiler-ci-bucket/tools/jtreg-6.1.1.zip
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -

git clone https://github.com/dragonwell-project/dragonwell11.git jdk-repo -b dragonwell_extended-11.0.21.18.9 jdk-repo

native=-nativepath:./test-image/hotspot/jtreg/native
args='-XX:+UseCompactObjectHeaders'
test=runtime/SharedArchiveFile/NonBootLoaderClasses.java

jtreg  -nr -v:fail,error -w tmp  $args $native $test
```

类似用例:

runtime/SharedArchiveFile/NonBootLoaderClasses.java
runtime/SharedArchiveFile/PrintSharedArchiveAndExit.java
runtime/appcds/CommandLineFlagCombo.java
runtime/appcds/cacheObject/OpenArchiveRegion.java
runtime/appcds/sharedStrings/IncompatibleOptions.java

【对比测试】

dragonwell11 release版本和上游temurin均不支持此配置.

【用例日志】

```
STDOUT:
STDERR:

ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'archive is valid' missing from stdout/stderr
REASON: Assumed action based on file name: run main PrintSharedArchiveAndExit 
TIME:   0.987 seconds
messages:
command: main PrintSharedArchiveAndExit
reason: Assumed action based on file name: run main PrintSharedArchiveAndExit 
Mode: othervm
Additional options from @modules: --add-modules java.base,java.management --add-exports java.base/jdk.internal.misc=ALL-UNNAMED
elapsed time (seconds): 0.987
configuration:
Boot Layer
  add modules: java.base java.management   
  add exports: java.base/jdk.internal.misc ALL-UNNAMED

STDOUT:
Command line: [/tmp/tone/run/jtreg/binary-download/dragonwell-11.0.20.17+8-GA/bin/java -cp /tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/7/runtime/SharedArchiveFile/PrintSharedArchiveAndExit.d:/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/runtime/SharedArchiveFile:/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/7/test/lib:/tmp/tone/run/jtreg/jdk-repo/test/lib:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar -Djdk.lang.processReaperUseDefaultStackSize=true -Dtest.wisp.socketAddress=www.alibabacloud.com -XX:+UseCompactObjectHeaders -ea -esa -Xshare:dump -Xlog:cds,cds+hashtables -XX:SharedArchiveFile=./PrintSharedArchiveAndExit.jsa ]
[2023-12-15T00:23:33.202865Z] Gathering output for process 634218
[ELAPSED: 606 ms]
[STDERR]

[STDOUT]
[0.007s][info][cds] narrow_klass_base = 0x0000000800000000, narrow_klass_shift = 3
[0.007s][info][cds] Allocated temporary class space: 1073741824 bytes at 0x00000008c0000000
Allocated shared space: 3221225472 bytes at 0x0000000800000000
[0.008s][info][cds] Expanding shared spaces by 1048576 bytes [total   1048576 bytes ending at 0x800100000]
Loading classes to share ...
Loading classes to share: done.
[0.182s][info][cds] Shared spaces: preloaded 1190 classes
Rewriting and linking classes ...
Rewriting and linking classes: done
Number of classes 1256
    instance classes   =  1195
    obj array classes  =    53
    type array classes =     8
Updating ConstMethods ... done. 
Removing unshareable information ... done. 
Scanning all metaspace objects ... 
Allocating RW objects ... 
[0.223s][info][cds] Expanding shared spaces by 1048576 bytes [total   2097152 bytes ending at 0x800200000]
[0.232s][info][cds] Expanding shared spaces by 1048576 bytes [total   3145728 bytes ending at 0x800300000]
[0.242s][info][cds] Expanding shared spaces by 1048576 bytes [total   4194304 bytes ending at 0x800400000]
Allocating RO objects ... 
[0.266s][info][cds] Expanding shared spaces by 1048576 bytes [total   5242880 bytes ending at 0x800500000]
[0.269s][info][cds] Expanding shared spaces by 1048576 bytes [total   6291456 bytes ending at 0x800600000]
[0.273s][info][cds] Expanding shared spaces by 1048576 bytes [total   7340032 bytes ending at 0x800700000]
[0.283s][info][cds,hashtables] Expanded _new_loc_table to 16174
[0.283s][info][cds           ] Expanding shared spaces by 1048576 bytes [total   8388608 bytes ending at 0x800800000]
[0.290s][info][cds           ] Expanding shared spaces by 1048576 bytes [total   9437184 bytes ending at 0x800900000]
[0.300s][info][cds           ] Expanding shared spaces by 1048576 bytes [total  10485760 bytes ending at 0x800a00000]
[0.311s][info][cds           ] Expanding shared spaces by 1048576 bytes [total  11534336 bytes ending at 0x800b00000]
Relocating embedded pointers ... 
Relocating external roots ... 
Dumping symbol table ...
[0.539s][info][cds,hashtables] Shared symbol table stats -------- base: 0x0000000800000000
[0.539s][info][cds,hashtables] Number of entries       :     37593
[0.539s][info][cds,hashtables] Total bytes used        :    335752
[0.539s][info][cds,hashtables] Average bytes per entry :     8.931
[0.539s][info][cds,hashtables] Average bucket size     :     4.000
[0.539s][info][cds,hashtables] Variance of bucket size :     3.945
[0.539s][info][cds,hashtables] Std. dev. of bucket size:     1.986
[0.539s][info][cds,hashtables] Empty buckets           :       166
[0.539s][info][cds,hashtables] Value_Only buckets      :       650
[0.539s][info][cds,hashtables] Other buckets           :      8582
Dumping objects to closed archive heap region ...
[0.547s][info][cds,hashtables] Shared string table stats -------- base: 0x0000000800000000
[0.547s][info][cds,hashtables] Number of entries       :      6822
[0.547s][info][cds,hashtables] Total bytes used        :     60864
[0.547s][info][cds,hashtables] Average bytes per entry :     8.922
[0.547s][info][cds,hashtables] Average bucket size     :     4.001
[0.547s][info][cds,hashtables] Variance of bucket size :     4.475
[0.547s][info][cds,hashtables] Std. dev. of bucket size:     2.115
[0.547s][info][cds,hashtables] Empty buckets           :        38
[0.547s][info][cds,hashtables] Value_Only buckets      :       137
[0.547s][info][cds,hashtables] Other buckets           :      1530
Dumping objects to open archive heap region ...
Relocating SystemDictionary::_well_known_klasses[] ... 
Removing java_mirror ... done. 
[0.559s][info][cds           ] Expanding shared spaces by 1048576 bytes [total  12582912 bytes ending at 0x800c00000]
[0.560s][info][cds           ] Oopmap = 0x0000000800b01100 ( 13184 bytes) for heap region 0x00000007bfc00000 (  421888 bytes)
[0.560s][info][cds           ] Oopmap = 0x0000000800b04480 (  9088 bytes) for heap region 0x00000007bf800000 (  290816 bytes)
[0.570s][info][cds           ] Archive heap region 4 0x00000007bfc00000 - 0x00000007bfc67000 =   421888 bytes
[0.570s][info][cds           ] Archive heap region 5 0x0000000000000000 - 0x0000000000000000 =        0 bytes
[0.570s][info][cds           ] Archive heap region 6 0x00000007bf800000 - 0x00000007bf847000 =   290816 bytes
[0.570s][info][cds           ] Archive heap region 7 0x0000000000000000 - 0x0000000000000000 =        0 bytes
[0.570s][info][cds           ] Dumping shared data to file: 
[0.570s][info][cds           ]    ./PrintSharedArchiveAndExit.jsa
[0.571s][info][cds           ] Shared file region 0: 0x000021e8 bytes, addr 0x0000000800000000 file offset 0x00001000
[0.571s][info][cds           ] Shared file region 1: 0x003f1d50 bytes, addr 0x0000000800003000 file offset 0x00004000
[0.576s][info][cds           ] Shared file region 2: 0x00711800 bytes, addr 0x00000008003f5000 file offset 0x003f6000
[0.587s][info][cds           ] Shared file region 3: 0x00000a00 bytes, addr 0x0000000800b07000 file offset 0x00b08000
[0.587s][info][cds           ] Archive heap region 4 0x00000007bfc00000 - 0x00000007bfc67000 =   421888 bytes
[0.587s][info][cds           ] Shared file region 4: 0x00067000 bytes, addr 0x00000007bfc00000 file offset 0x00b09000
[0.587s][info][cds           ] Archive heap region 5 0x0000000000000000 - 0x0000000000000000 =        0 bytes
[0.587s][info][cds           ] Shared file region 5: 0x00000000 bytes, addr 0x0000000000000000 file offset 0x00b70000
[0.587s][info][cds           ] Archive heap region 6 0x00000007bf800000 - 0x00000007bf847000 =   290816 bytes
[0.587s][info][cds           ] Shared file region 6: 0x00047000 bytes, addr 0x00000007bf800000 file offset 0x00b70000
[0.588s][info][cds           ] Archive heap region 7 0x0000000000000000 - 0x0000000000000000 =        0 bytes
[0.588s][info][cds           ] Shared file region 7: 0x00000000 bytes, addr 0x0000000000000000 file offset 0x00bb7000
mc  space:      8680 [  0.1% of total] out of     12288 bytes [ 70.6% used] at 0x0000000800000000
rw  space:   4136272 [ 33.7% of total] out of   4136960 bytes [100.0% used] at 0x0000000800003000
ro  space:   7411712 [ 60.4% of total] out of   7413760 bytes [100.0% used] at 0x00000008003f5000
md  space:      2560 [  0.0% of total] out of      4096 bytes [ 62.5% used] at 0x0000000800b07000
st0 space:    421888 [  3.4% of total] out of    421888 bytes [100.0% used] at 0x00000007bfc00000
oa0 space:    290816 [  2.4% of total] out of    290816 bytes [100.0% used] at 0x00000007bf800000
total    :  12271928 [100.0% of total] out of  12279808 bytes [ 99.9% used]
[0.588s][info][cds           ] Detailed metadata info (excluding od/st regions; rw stats include md/mc regions):
[0.588s][info][cds           ]                         ro_cnt   ro_bytes     % |   rw_cnt   rw_bytes     % |  all_cnt  all_bytes     %
[0.588s][info][cds           ] --------------------+---------------------------+---------------------------+--------------------------
[0.588s][info][cds           ] Class               :        0          0   0.0 |     1256     814864  19.6 |     1256     814864   7.0
[0.588s][info][cds           ] Symbol              :    37593    1467176  19.8 |        0          0   0.0 |    37593    1467176  12.7
[0.588s][info][cds           ] TypeArrayU1         :     9193     272424   3.7 |     1195     242560   5.8 |    10388     514984   4.5
[0.588s][info][cds           ] TypeArrayU2         :     1901      77960   1.1 |     1195      82288   2.0 |     3096     160248   1.4
[0.588s][info][cds           ] TypeArrayU4         :     1359      85632   1.2 |        0          0   0.0 |     1359      85632   0.7
[0.588s][info][cds           ] TypeArrayU8         :     2007     186696   2.5 |     1195     143016   3.4 |     3202     329712   2.9
[0.588s][info][cds           ] TypeArrayOther      :        0          0   0.0 |        0          0   0.0 |        0          0   0.0
[0.588s][info][cds           ] Method              :        0          0   0.0 |    18766    1658608  40.0 |    18766    1658608  14.3
[0.588s][info][cds           ] ConstMethod         :    18766    2878704  38.8 |        0          0   0.0 |    18766    2878704  24.9
[0.588s][info][cds           ] MethodData          :        0          0   0.0 |        0          0   0.0 |        0          0   0.0
[0.588s][info][cds           ] ConstantPool        :     1195    1916920  25.9 |        0          0   0.0 |     1195    1916920  16.6
[0.588s][info][cds           ] ConstantPoolCache   :        0          0   0.0 |     1195    1194936  28.8 |     1195    1194936  10.3
[0.588s][info][cds           ] Annotations         :       53       1696   0.0 |        0          0   0.0 |       53       1696   0.0
[0.588s][info][cds           ] MethodCounters      :        0          0   0.0 |        0          0   0.0 |        0          0   0.0
[0.588s][info][cds           ] SymbolHashentry     :    37593     298152   4.0 |        0          0   0.0 |    37593     298152   2.6
[0.588s][info][cds           ] SymbolBucket        :     9398      37600   0.5 |        0          0   0.0 |     9398      37600   0.3
[0.588s][info][cds           ] StringHashentry     :     6822      54032   0.7 |        0          0   0.0 |     6822      54032   0.5
[0.588s][info][cds           ] StringBucket        :     1705       6832   0.1 |        0          0   0.0 |     1705       6832   0.1
[0.588s][info][cds           ] Other               :        0     127888   1.7 |        0      11240   0.3 |        0     139128   1.2
[0.588s][info][cds           ] --------------------+---------------------------+---------------------------+--------------------------
[0.588s][info][cds           ] Total               :   127585    7411712 100.0 |    24802    4147512 100.0 |   152387   11559224 100.0

[2023-12-15T00:23:33.795542Z] Waiting for completion for process 634218
[2023-12-15T00:23:33.795645Z] Waiting for completion finished for process 634218
Command line: [/tmp/tone/run/jtreg/binary-download/dragonwell-11.0.20.17+8-GA/bin/java -cp /tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/7/runtime/SharedArchiveFile/PrintSharedArchiveAndExit.d:/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/runtime/SharedArchiveFile:/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/7/test/lib:/tmp/tone/run/jtreg/jdk-repo/test/lib:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar -XX:+UnlockDiagnosticVMOptions -XX:SharedArchiveFile=./PrintSharedArchiveAndExit.jsa -XX:+PrintSharedArchiveAndExit -version ]
[2023-12-15T00:23:33.798467Z] Gathering output for process 634528
[ELAPSED: 30 ms]
[STDERR]
An error has occurred while processing the shared archive file.
The shared archive file's UseCompactObjectHeaders setting (enabled) does not equal the current UseCompactObjectHeaders setting (disabled).

[STDOUT]
[0.002s][info][class,path] opened: /tmp/tone/run/jtreg/binary-download/dragonwell-11.0.20.17+8-GA/lib/modules
Error occurred during initialization of VM
Unable to use shared archive.

[2023-12-15T00:23:33.826745Z] Waiting for completion for process 634528
[2023-12-15T00:23:33.826862Z] Waiting for completion finished for process 634528
[2023-12-15T00:23:33.827016Z] Waiting for completion for process 634528
[2023-12-15T00:23:33.827077Z] Waiting for completion finished for process 634528
STDERR:
 stdout: [[0.002s][info][class,path] opened: /tmp/tone/run/jtreg/binary-download/dragonwell-11.0.20.17+8-GA/lib/modules
Error occurred during initialization of VM
Unable to use shared archive.
];
 stderr: [An error has occurred while processing the shared archive file.
The shared archive file's UseCompactObjectHeaders setting (enabled) does not equal the current UseCompactObjectHeaders setting (disabled).
]
 exitValue = 1

java.lang.RuntimeException: 'archive is valid' missing from stdout/stderr 

	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:163)
	at PrintSharedArchiveAndExit.main(PrintSharedArchiveAndExit.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:955)

JavaTest Message: Test threw exception: java.lang.RuntimeException: 'archive is valid' missing from stdout/stderr 

JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: 'archive is valid' missing from stdout/stderr


```

【版本信息】
```
[root@VM20190228-137 a11]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;java -version; java -Xinternalversion
Linux VM20190228-137 5.10.134-14.al8.x86_64 #1 SMP Thu Apr 27 16:46:29 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:           15Gi       753Mi       288Mi       842Mi        14Gi        13Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
BIOS Vendor ID:      Alibaba Cloud
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
BIOS Model name:     pc-i440fx-2.1
Stepping:            4
CPU MHz:             2500.012
BogoMIPS:            5000.02
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0-3
openjdk version "11.0.21.17" 2023-10-17
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition)-11.0.20.17+8-GA (build 11.0.21.17+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition)-11.0.20.17+8-GA (build 11.0.21.17+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.21.17+8) for linux-amd64 JRE (11.0.21.17+8), built on Dec 12 2023 03:41:33 by "" with gcc 7.5.0
```

**Comment by owanqian** [comment]
二进制包重新构建. 构建测试后如果有问题,再打开.
