### ISSUE TITLE
【ajdk8】默认选项下，4个CA相关的测试用例：couldn't determine EE certificate status

### ISSUE THREAD

**Issue by owanqian** [dragonwell-releng/dragonwell-adoptium#328]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/268494

【环境准备】
```
wget -O binary.tar.gz http://114.55.64.175:8666/ajdk-backup/8.16.20_fp2-test-ajdk_fp/OpenJDK8U-jdk_aarch64_linux_ajdk_2024-01-12-08-54.tar.gz
mkdir binary-download 
tar xzvf binary.tar.gz -C binary-download
cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -


wget -nv http://114.55.64.175:8666/compiler-ci-bucket/tools/jtreg5.1-b01.zip -O jtreg.zip
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
git clone -b v8.16.20_fp https://codeup.aliyun.com/5f4e0dfe6207a1a8b17fa7cf/compiler-test/jdk8u.git jdk-repo
test=security/infra/java/security/cert/CertPathValidator/certification/SSLCA.java
args='-Xmixed'
jtreg -w tmp -nr -v:fail,error $args $test
```

涉及的测试用例：
security/infra/java/security/cert/CertPathValidator/certification/GlobalSignR6CA.java
security/infra/java/security/cert/CertPathValidator/certification/LetsEncryptCA.java
security/infra/java/security/cert/CertPathValidator/certification/SSLCA.java
sun/security/ssl/X509TrustManagerImpl/CacertsLimit.java

【对比版本】

ajdk8 fp版本，测试通过。

wget http://114.55.64.175:8666/ajdk-backup/8.16.20_fp1/8.16.20_fp1_aarch64.tar.gz

```
[root@iZbp10m5gxyeaz1iykchhvZ bin]# ./java -version; ./java -Xinternalversion
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Alibaba 8.16.20_fp1) (build 1.8.0_332-b)
OpenJDK 64-Bit Server VM (Alibaba 8.16.20_fp1) (build 25.332-b-internal, mixed mode)
OpenJDK 64-Bit Server VM (25.332-b-internal) for linux-aarch64 JRE (1.8.0_332-b), built on Jul 19 2022 03:20:43 by "root" with gcc 4.8.5 20150623 (Red Hat 4.8.5-44)

```

【用例日志】

```
certpath: AdaptableX509CertSelector.match: subject key IDs don't match. Expected: [4, 20, -82, 108, 5, -93, -109, 19, -30, -94, -25, -30, -41, 28, -42, -57, -16, 127, -56, 103, 83, -96] Cert's: [4, 20, -45, -108, -118, 76, 98, 19, 42, 25, 46, -52, -81, 114, -118, 125, 54, -41, -102, 28, -36, 103]
certpath: NO - don't try this trustedCert
certpath: AdaptableX509CertSelector.match: subject key IDs don't match. Expected: [4, 20, -82, 108, 5, -93, -109, 19, -30, -94, -25, -30, -41, 28, -42, -57, -16, 127, -56, 103, 83, -96] Cert's: [4, 20, 61, -26, 41, 72, -101, -22, 7, -54, 33, 68, 74, 38, -34, 110, -34, -46, -125, -48, -97, 89]
certpath: NO - don't try this trustedCert
certpath: AdaptableX509CertSelector.match: subject key IDs don't match. Expected: [4, 20, -82, 108, 5, -93, -109, 19, -30, -94, -25, -30, -41, 28, -42, -57, -16, 127, -56, 103, 83, -96] Cert's: [4, 20, -19, 68, 25, -64, -45, -16, 6, -117, -18, -92, 123, -66, 66, -25, 38, 84, -56, -114, 54, 118]
certpath: NO - don't try this trustedCert
java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status
        at ValidatePathWithParams.validate(ValidatePathWithParams.java:177)
        at GlobalSignR6CA.main(GlobalSignR6CA.java:203)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:879)

JavaTest Message: Test threw exception: java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status

```

【版本信息】
```
[root@iZbp10m5gxyeaz1iykchhvZ jtreg]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;java -version; java -Xinternalversion
Linux iZbp10m5gxyeaz1iykchhvZ 5.10.134-15.an8.aarch64 #1 SMP Thu Jul 20 00:33:45 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
NAME="Anolis OS"
VERSION="8.8"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.8"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.8"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

              total        used        free      shared  buff/cache   available
Mem:           61Gi       701Mi        57Gi       0.0Ki       3.2Gi        59Gi
Swap:            0B          0B          0B
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  1
Core(s) per socket:  32
Socket(s):           1
NUMA node(s):        1
Vendor ID:           ARM
BIOS Vendor ID:      Alibaba Cloud
Model:               0
Model name:          Neoverse-N2
BIOS Model name:     virt-rhel7.6.0
Stepping:            r0p0
CPU MHz:             3000.000
CPU max MHz:         3000.0000
CPU min MHz:         3000.0000
BogoMIPS:            100.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            1024K
L3 cache:            65536K
NUMA node0 CPU(s):   0-31
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs sb dcpodp sve2 sveaes svepmull svebitperm svesha3 svesm4 flagm2 frint svei8mm svebf16 i8mm bf16 dgh
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Alibaba 8.16.20_fp1) (build 1.8.0_332-b0)
OpenJDK 64-Bit Server VM (Alibaba 8.16.20_fp1) (build 25.332-b0-internal, mixed mode)
OpenJDK 64-Bit Server VM (25.332-b0-internal) for linux-aarch64 JRE (1.8.0_332-b0), built on Jan 12 2024 08:59:26 by "root" with gcc 4.8.5 20150623 (Red Hat 4.8.5-44)

```

**Comment by sendaoYan** [comment]
在这里跟踪：
https://aone.alibaba-inc.com/v2/project/355606/bug/54530484# 《[ajdk8][8.16.20_fp2]相比8.16.20_fp1新增4个证书相关失败用例》
