### ISSUE TITLE
【regress】anolis86环境ajdk11运行serviceability/sa/ClhsdbJstackXcompStress.java用例报错

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-releng/dragonwell-adoptium#34]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148193?tab=1

```log
 stderr: [Warning: the type "NegVFNode" (declared in the remote VM in VMStructs::localHotSpotVMTypes) had its size declared as 64 twice. Continuing.
Warning: the type "NegVDNode" (declared in the remote VM in VMStructs::localHotSpotVMTypes) had its size declared as 64 twice. Continuing.
Warning: the type "MaxReductionVNode" (declared in the remote VM in VMStructs::localHotSpotVMTypes) had its size declared as 56 twice. Continuing.
Warning: the type "MinReductionVNode" (declared in the remote VM in VMStructs::localHotSpotVMTypes) had its size declared as 56 twice. Continuing.
]
 exitValue = 0

java.lang.RuntimeException: stderr was not empty
	at jdk.test.lib.process.OutputAnalyzer.stderrShouldBeEmpty(OutputAnalyzer.java:104)
	at ClhsdbJstackXcompStress.runJstackInLoop(ClhsdbJstackXcompStress.java:77)
	at ClhsdbJstackXcompStress.main(ClhsdbJstackXcompStress.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:991)
 LingeredApp stdout: [CompileCommand: dontinline LingeredAppWithRecComputation.factorial
CompileCommand: compileonly LingeredAppWithRecComputation.testLoop
CompileCommand: compileonly LingeredAppWithRecComputation.factorial
];
 LingeredApp stderr: []
 LingeredApp exitValue = 0
java.lang.RuntimeException: stderr was not empty
	at jdk.test.lib.process.OutputAnalyzer.stderrShouldBeEmpty(OutputAnalyzer.java:104)
	at ClhsdbJstackXcompStress.runJstackInLoop(ClhsdbJstackXcompStress.java:77)
	at ClhsdbJstackXcompStress.main(ClhsdbJstackXcompStress.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:991)
```
测试环境：

![image](https://user-images.githubusercontent.com/24123821/221132121-e77ce90a-f0f3-4d2d-98ec-33f863d8f982.png)

ubuntu20环境同样的测试没有问题：
![image](https://user-images.githubusercontent.com/24123821/221131656-18474836-b96a-4f61-9cae-f13275fd5725.png)

anolis86环境上，使用dragonwell11没有问题：

![image](https://user-images.githubusercontent.com/24123821/221131852-22066d42-5ef6-409d-bc2f-e57fb224aad5.png)

**Comment by sendaoYan** [comment]
alios7环境也能复现

**Comment by zhengxiaolinX** [comment]
已修复，在 WIP 上。

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14142409?file=96e787b203de06c51f05bcd814351c9372cea722
